
-- =============================================================
-- -------------------------------------------------------------
-- --  --  --  TABLES DUMMY DATA  --  --  --  --  --  --  --  --
-- -------------------------------------------------------------
-- =============================================================

insert into Food_Groups (name, description,link_to_image,image_description) 
values ('Λαχανικά',
'Όλα τα ωμά λαχανικά, (π.χ. μαρούλι, λάχανο, καρότο, ντομάτα, αγγούρι, κρεμμύδι κ.ά.)
Όλα τα μαγειρεμένα λαχανικά (π.χ. μπρόκολο, κουνουπίδι, κολοκυθάκια, χόρτα, παντζάρια κ.ά.)
Τα αμυλώδη λαχανικά (π.χ. αρακάς, καλαμπόκι, κολοκύθα)
ΔΕΝ περιλαμβάνεται η πατάτα και οι ποικιλίες της', 
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Φρούτα',
'Όλα τα ωμά φρούτα (π.χ. πορτοκάλι, μήλο, αχλάδι, μπανάνα, ροδάκινο κ.ά.)
Όλα τα αποξηραμένα φρούτα (π.χ. δαμάσκηνα, σταφίδες, βερίκοκα κ.ά.)
Οι φυσικοί χυμοί φρούτων (100% χωρίς προσθήκη ζάχαρης)',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Δημητριακά (ψωμί, ρύζι, ζυμαρικά) και Πατάτες',
'Τα δημητριακά:
Σιτάρι, βρόμη, κριθάρι, σίκαλη κ.ά.
Ρύζι

Τα προϊόντα δημητριακών:
Αλεύρι
Ψωμί
Απλά αρτοσκευάσματα π.χ. φρυγανιές, παξιμάδια, κριτσίνια, κράκερ
Σύνθετα αρτοσκευάσματα π.χ. ζύμες, πίτες
Ζυμαρικά π.χ. μακαρόνια, κριθαράκι, χυλοπίτες
Διάφορα προϊόντα δημητριακών π.χ. πλιγούρι,τραχανάς
Δημητριακά πρωινού
Η πατάτα και οι ποικιλίες της',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Γάλα και γαλακτοκομικά προϊόντα',
'Το γάλα
Τα γαλακτοκομικά προϊόντα (π.χ. γιαούρτι, τυρί, ξινόγαλο κ.ά.)
ΔΕΝ περιλαμβάνεται το βούτυρο (συγκαταλέγεται στα λίπη και έλαια)',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Όσπρια',
'Οι φακές
Τα φασόλια
Τα ρεβίθια
Η φάβα
Τα ξερά κουκιά
Οι ποικιλίες όλων των παραπάνω',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Κόκκινο κρέας',
'Μοσχάρι, βοδινό
Χοιρινό
Αρνί, πρόβατο
Κατσίκι, γίδα
Κυνήγι: π.χ. αγριογούρουνο, ελάφι, ζαρκάδι
Όλα τα επεξεργασμένα προϊόντα των παραπάνω',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Λευκό κρέας',
'Κοτόπουλο
Γαλοπούλα
Πάπια
Κουνέλι
Κυνήγι: π.χ. φασιανός, ορτύκι, πέρδικα
Όλα τα επεξεργασμένα προϊόντα των παραπάνω',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Αυγά',
'ολοι ξερουν τι είναι τα αυγά μπρο',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Ψάρια και θαλασσινά',
'Τα ψάρια (π.χ. σαρδέλα, μαρίδα, γόπα, γαύρος, αθερίνα, ροφός, συναγρίδα, σφυρίδα, μπακαλιάρος, γαλέος, τόνος, λαβράκι, σαργός, τσιπούρα, λυθρίνι)
Τα θαλασσινά (μαλάκια, οστρακοειδή, οστρακόδερμα) π.χ. καλαμάρι, σουπιά, χταπόδι, γαρίδα, μύδια, στρείδια.',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων'),

('Προστιθέμενα λίπη και έλαια, ελιές και ξηροί καρποί',
'Τα προστιθέμενα λίπη και έλαια:
Ελαιόλαδο
Άλλα έλαια φυτικής προέλευσης (σπορέλαια): ηλιέλαιο, καλαμποκέλαιο, σογιέλαιο, σησαμέλαιο κ.ά.
Μαργαρίνη
Βούτυρο
Οι ελιές
Οι ξηροί καρποί
Καρύδια, αμύγδαλα, φιστίκια, φουντούκια κ.ά.
Ηλιόσποροι, σουσάμι κ.ά.
Προϊόντα επάλειψης που προέρχονται από τα παραπάνω (π.χ., ταχίνι)',
'https://i.pinimg.com/originals/5c/96/a0/5c96a0c3414b41708984610fc38e456d.jpg', 'Εικόνα με τις ομάδες τροφίμων');

insert into National_Cuisines (name,link_to_image,image_description) 
values ('Παλαιστινιακή κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of palestinian cuisine'),
('Αυστριακή κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of austrian cuisine'),
('Βιετναμέζικη κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of vietnamese cuisine'),
('Γαλλική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of french cuisine'),
('Γεωργιανή κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of georgian cuisine'),
('Ελληνική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of greek cuisine'),
('Εσθονική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of estonian cuisine'),
('Ιαπωνική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of japanese cuisine'),
('Κουζίνα της Ινδίας', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of indian cuisine'),
('Ιταλική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of italian cuisine'),
('Κινέζικη κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of chinese cuisine'),
('Ποντιακή ελληνική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of pontic greek cuisine'),
('Κυπριακή κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of cypriot cuisine'),
('Λευκορωσική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of belarusian cuisine'),
('Μολδαβική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of moldovan cuisine'),
('Ουκρανική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of ukrainian cuisine'),
('Πολωνική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of polish cuisine'),
('Ρωσική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of russian cuisine'),
('Σερβική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of serbian cuisine'),
('Ταϊλανδέζικη κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of thai cuisine'),
('Τουρκική κουζίνα', 'https://en.wikipedia.org/wiki/List_of_cuisines#/media/File:Floris_Claesz._van_Dyck_001.jpg', 'Photo of turkish cuisine')


 insert into Episodes (episode_year, episode_number) 
 values (2025, 1),
    (2025, 2),
    (2025, 3),
    (2025, 4),
    (2025, 5),
    (2025, 6),
    (2025, 7),
    (2025, 8),
    (2025, 9),
    (2025, 10),
    (2026, 1),
    (2026, 2),
    (2026, 3),
    (2026, 4),
    (2026, 5),
    (2026, 6),
    (2026, 7),
    (2026, 8),
    (2026, 9),
    (2026, 10),
    (2027, 1),
    (2027, 2),
    (2027, 3),
    (2027, 4),
    (2027, 5),
    (2027, 6),
    (2027, 7),
    (2027, 8),
    (2027, 9),
    (2027, 10),
    (2028, 1),
    (2028, 2),
    (2028, 3),
    (2028, 4),
    (2028, 5),
    (2028, 6),
    (2028, 7),
    (2028, 8),
    (2028, 9),
    (2028, 10),
    (2029, 1),
    (2029, 2),
    (2029, 3),
    (2029, 4),
    (2029, 5),
    (2029, 6),
    (2029, 7),
    (2029, 8),
    (2029, 9),
    (2029, 10),
    (2030, 1),
    (2030, 2),
    (2030, 3),
    (2030, 4),
    (2030, 5),
    (2030, 6),
    (2030, 7),
    (2030, 8),
    (2030, 9),
    (2030, 10);

INSERT INTO Cooks (full_name, phone_number, y_of_birth, ys_of_exp, level,link_to_image,image_description) 
VALUES ('John Doe', '123-456-7890', 1980, 10, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Jane Smith', '234-567-8901', 1982, 12, 'A΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Alice Johnson', '345-678-9012', 1984, 8, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Κατερίνα Αντωνοπούλου', '693-767-0768', 2003, 3, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Charlie Davis', '567-890-1234', 1988, 5, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Eva Martinez', '678-901-2345', 1990, 7, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Frank Harris', '789-012-3456', 1992, 9, 'A΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Grace Lee', '890-123-4567', 1994, 11, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Hannah Clark', '901-234-5678', 1996, 6, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Ivy Lewis', '012-345-6789', 1998, 4, 'A΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Jack Walker', '123-456-7890', 1981, 13, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Karen Young', '234-567-8901', 1983, 14, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Leo Hall', '345-678-9012', 1985, 9, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Mia King', '456-789-0123', 1987, 12, 'βοηθός αρχιμάγειρα', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Nora Wright', '567-890-1234', 1989, 10, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Oscar Scott', '678-901-2345', 1991, 7, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Pamela Green', '789-012-3456', 1993, 5, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Quincy Adams', '890-123-4567', 1995, 8, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Ruby Baker', '901-234-5678', 1997, 6, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Steve Mitchell', '012-345-6789', 1999, 3, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Δαμιανός Ρούπι', '697-546-3891', 2000, 5, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Umar Nelson', '234-567-8901', 1982, 18, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Violet Perez', '345-678-9012', 1984, 16, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Walter Moore', '456-789-0123', 1986, 14, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Xena Turner', '567-890-1234', 1988, 12, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Yara White', '678-901-2345', 1990, 10, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Zachary Hall', '789-012-3456', 1992, 8, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Amber Allen', '890-123-4567', 1994, 6, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/female-chef-smiling-in-commercial-kitchen-gm1096973130-294436676', 'Chef Amber Allen smiling in a commercial kitchen'),
('Brian Young', '901-234-5678', 1996, 4, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Cathy Flores', '012-345-6789', 1998, 2, 'A΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('David Evans', '123-456-7890', 1981, 19, 'βοηθός αρχιμάγειρα', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Elaine Brooks', '234-567-8901', 1983, 17, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Fred Simmons', '345-678-9012', 1985, 15, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Gloria Hayes', '456-789-0123', 1987, 13, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Henry Reed', '567-890-1234', 1989, 11, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Isabella Ramirez', '678-901-2345', 1991, 9, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Jason Bell', '789-012-3456', 1993, 7, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Kelly Russell', '890-123-4567', 1995, 5, 'βοηθός αρχιμάγειρα', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Larry Griffin', '901-234-5678', 1997, 3, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Monica Torres', '012-345-6789', 1999, 1, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Nathan Cooper', '123-456-7890', 1982, 18, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Olivia Rivera', '234-567-8901', 1984, 16, 'βοηθός αρχιμάγειρα', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Patrick Sanders', '345-678-9012', 1986, 14, 'βοηθός αρχιμάγειρα', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Βικ Κορακοβούνη', '698-716-9068', 2001, 5, 'αρχιμάγειρας (σεφ)', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Rebecca Long', '567-890-1234', 1990, 10, 'A΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Samuel Foster', '678-901-2345', 1992, 8, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Tiffany Ross', '789-012-3456', 1994, 6, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Ulysses Fisher', '890-123-4567', 1996, 4, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Victoria Howard', '901-234-5678', 1998, 2, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('William Ward', '012-345-6789', 1983, 17, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Xavier Bryant', '123-456-7890', 1985, 15, 'βοηθός αρχιμάγειρα', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Yvonne Alexander', '234-567-8901', 1987, 13, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Zane Hernandez', '345-678-9012', 1989, 11, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Anna Phillips', '456-789-0123', 1991, 9, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/african-american-woman-bakers-looking-at-camera-chef-baker-in-a-chef-dress-and-hat-gm1389857295-447006096', 'Chef portrait while cooking'),
('Brandon Campbell', '567-890-1234', 1993, 7, 'Γ΄ μάγειρας', 'https://www.istockphoto.com/photo/gourmet-chef-cooking-in-a-commercial-kitchen-gm866699668-144148073', 'Chef portrait while cooking'),
('Claire Mitchell', '678-901-2345', 1995, 5, 'βοηθός αρχιμάγειρα','https://www.istockphoto.com/photo/chef-preparing-food-in-kitchen-gm1076964214-288547520', 'Chef preparing food in the kitchen'),
('Derek Carter', '789-012-3456', 1997, 3, 'A΄ μάγειρας', 'https://www.istockphoto.com/photo/chef-preparing-food-in-kitchen-gm1076964214-288547520', 'Chef Derek Carter preparing food in the kitchen'),
('Elena Peterson', '890-123-4567', 1999, 1, 'Β΄ μάγειρας', 'https://www.istockphoto.com/photo/young-chef-cooking-in-the-kitchen-gm1150138963-310185680', 'Chef Elena Peterson cooking in the kitchen');

insert into Thematic_Units (name, description) 
values ('Πιάτα για Φοιτητές', 'Εύκολες και γρήγορες συνταγές για φοιτητές'),
('Πιάτα light-Ευ ζην', 'Ελαφριά, υγιεινά και light πιάτα'),
('Άγιος Βαλεντίνος', 'Γιατί ο έρωτας περνάει από το στομάχι'),
('Καλοκαιρινές συνταγές', 'Ελαφριά, δροσερά γεύματα'),
('Χειμωνιάτικες συνταγές', 'Ζεστά χειμωνιάτικα κυρίως πιάτα και σούπες'),
('Πάσχα', 'Για το γιορτινό πασχαλινό τραπέζι'),
('Χριστούγεννα', 'Αλμυρές και γλυκές χριστουγεννιάτικες συνταγές'),
('Νηστήσιμα-Vegan', 'Χορτοφαγικά και νηστήσιμα πιάτα'), 
('BBQ', 'Συνταγές για barbeque στην ψησταριά'),
('Παιδικές συνταγές', 'Μενού για τους παιδικούς μας φίλους'),
('Επίσημο δείπνο', 'Συνταγές και ιδέες που θα κερδίσουν τους πιο απαιτητικούς καλεσμένους'),
('Leftovers', 'Φρέσκιες συνταγές για να αξιοποιηθούν τα απομεινάρια και να μην πάει τίποτα χαμένο');

insert into Tags (name,link_to_image,image_description) 
values ('brunch','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('quick-lunch',,'https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('κρύο πιάτο','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('finger-food','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('ορεκτικά','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'),
('μαρμελάδες','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('ζύμες','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('ντιπ & σάλτσες','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('φρούτα','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('κεφτέδες','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('ψωμιά','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('σαλάτες','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού'), 
('σάντουιτς','https://www.nutritionadvance.com/wp-content/uploads/2021/10/popular-types-of-diet-1024x683.jpg', 'Διάφορα είδη φαγητού');

insert into Meal_Type (name,link_to_image,image_description)
values ('Πρωινό','https://gr.pinterest.com/pin/264656915589987954/','Εικόνα με τα είδη γευμάτων'),
('Πρόγευμα','https://gr.pinterest.com/pin/264656915589987954/','Εικόνα με τα είδη γευμάτων'),
('Γεύμα','https://gr.pinterest.com/pin/264656915589987954/','Εικόνα με τα είδη γευμάτων'),
('Απογευματινό','https://gr.pinterest.com/pin/264656915589987954/','Εικόνα με τα είδη γευμάτων'),
('Δείπνο','https://gr.pinterest.com/pin/264656915589987954/','Εικόνα με τα είδη γευμάτων');

 insert into Equipment (name, instructions,link_to_image,image_description)
 values ('μπλέντερ', 'Για να ανακατεύουμε τα υλικά σε μια ομαλή συνοχή','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('επεξεργαστής τροφίμων', 'Για να κόβουμε, κόβουμε σε φέτες, τρίβουμε, αλέθουμε και πολτοποιούμε τα τρόφιμα γρήγορα','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('σταθερός μίξερ', 'Για να ανακατεύουμε, ζυμώνουμε και χτυπάμε υλικά','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('χειρός μίξερ', 'Για να ανακατεύουμε και να χτυπάμε υλικά','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('αργός μαγειρευτής (crockpot)', 'Για να μαγειρεύουμε τα τρόφιμα αργά σε χαμηλή θερμοκρασία για αρκετές ώρες','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('χύτρα ταχύτητας', 'Για να μαγειρεύουμε τα τρόφιμα γρήγορα υπό υψηλή πίεση','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('φριτέζα αέρα', 'Για να μαγειρεύουμε τα τρόφιμα χρησιμοποιώντας κυκλοφορία ζεστού αέρα','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('instant pot', 'Για να λειτουργεί ως πολυλειτουργική συσκευή μαγειρέματος','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('φούρνος μικροκυμάτων', 'Για να ζεσταίνουμε και να μαγειρεύουμε τα τρόφιμα χρησιμοποιώντας ακτινοβολία μικροκυμάτων','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('φρυγανιέρα', 'Για να φρυγανίζουμε ψωμί και μπέιγκελ','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('φούρνος φρυγανιέρας', 'Για να φρυγανίζουμε, ψήνουμε, ψήνουμε στη σχάρα και να ξαναζεσταίνουμε τα τρόφιμα','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('ηλεκτρική ψησταριά', 'Για να ψήνουμε τα τρόφιμα σε εσωτερικό χώρο','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('ολλανδικός φούρνος', 'Για να μαγειρεύουμε μια ποικιλία πιάτων, συχνά χρησιμοποιούμενο για βραστά και ψήσιμο','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('συσκευή ακριβείας sous vide', 'Για να μαγειρεύουμε τα τρόφιμα σε ακριβή θερμοκρασία σε λουτρό νερού','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('βυθιζόμενο μπλέντερ', 'Για να ανακατεύουμε τα υλικά απευθείας στην κατσαρόλα ή το δοχείο','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('ηλεκτρικός βραστήρας', 'Για να βράζουμε νερό γρήγορα','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('μαγειρευτής ρυζιού', 'Για να μαγειρεύουμε ρύζι αυτόματα','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('βαφλιέρα', 'Για να μαγειρεύουμε βάφλες','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('μηχανή ποπκόρν', 'Για να φτιάχνουμε ποπκόρν','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής'),
('αποχυμωτής', 'Για να εξάγουμε χυμό από φρούτα και λαχανικά','https://www.seriouseats.com/thmb/K_YR7faVfttU6J1KLGkRH85Gkn8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2017__06__20190610-kitchen-starter-equipment-vicky-wasik-1-33650db9ee6a4b5982dc8a18d1c6ef90.jpg','Εικόνα με εξοπλισμό μαγειρικής');

INSERT INTO Ingredients (name, calories_per_100, group_id)
VALUES
('αλεύρι', 364, 3),
('γιαούρτι', 61, 4),
('ντομάτα', 18, 1),
('πορτοκάλι', 43, 2),
('ρύζι', 130, 3),
('γάλα', 61, 4),
('καρότο', 41, 1),
('μήλο', 52, 2),
('μακαρόνια', 131, 3),
('τυρί', 356, 4),
('μπρόκολο', 34, 1),
('σταφίδες', 299, 2),
('πατάτα', 77, 3),
('φέτα', 264, 4),
('κολοκύθι', 17, 1),
('μπανάνα', 89, 2),
('κριθαράκι', 123, 3),
('ξινόγαλο', 64, 4),
('λαχανίδα', 15, 1),
('ροδάκινο', 39, 2),
('φρυγανιές', 242, 3),
('φακές', 341, 5),
('κρεμμύδι', 40, 1),
('βερίκοκο', 48, 2),
('κριτσίνια', 425, 3),
('φασόλια', 341, 5),
('σπανάκι', 23, 1),
('χυμός πορτοκαλιού', 45, 2),
('πλιγούρι', 123, 3),
('ρεβίθια', 164, 5),
('αγγούρι', 15, 1),
('δάφνη', 313, 2),
('τραχανάς', 322, 3),
('φάβα', 88, 5),
('πιπεριά', 20, 1),
('χυμός μήλου', 48, 2),
('ψωμί', 250, 3),
('κουκιά', 145, 5),
('παντζάρι', 43, 1),
('αχλάδι', 42, 2),
('ζύμη', 299, 3),
('μοσχάρι', 250, 6),
('κολοκύθα', 17, 1),
('χοιρινό', 280, 6),
('παξιμάδι', 360, 3),
('αρνί', 282, 6),
('κοτόπουλο', 219, 7),
('φασιανός', 158, 7),
('γάλα αμυγδάλου', 13, 4),
('καλαμπόκι', 86, 1),
('γαλοπούλα', 109, 7),
('πάπια', 337, 7),
('κουνέλι', 173, 7),
('ελαιόλαδο', 884, 8),
('καρύδια', 618, 8),
('φιστίκια', 557, 8),
('αρακάς', 116, 1),
('κολοκυθάκια', 16, 1),
('χαρουπόμελο', 290, 2),
('σογιέλαιο', 884, 8),
('μαργαρίνη', 717, 8),
('ελιές', 115, 8),
('αμύγδαλα', 575, 8),
('σησαμέλαιο', 884, 8),
('παπαρουνόσπορος', 570, 8),
('βούτυρο', 717, 8),
('ταχίνι', 593, 8),
('ηλιόσποροι', 584, 8),
('φουντούκια', 657, 8),
('κάρδαμο', 330, 1),
('γαλέτα', 411, 3),
('σαρδέλα', 208, 9),
('γαύρος', 151, 9),
('αθερίνα', 130, 9),
('καλαμάρι', 100, 9),
('σουπιά', 79, 9),
('χταπόδι', 57, 9),
('γαρίδα', 71, 9),
('μύδια', 60, 9),
('στρείδια', 90, 9),
('αγκινάρες', 47, 1),
('καρκινάκια', 90, 9),
('καβούρι', 83, 9),
('λαβράκι', 97, 9),
('τσιπούρα', 115, 9),
('λυθρίνι', 115, 9),
('μαρίδα', 86, 9),
('συναγρίδα', 139, 9),
('σφυρίδα', 95, 9),
('μπακαλιάρος', 82, 9),
('καρύκευμα', 120, 10),
('ανανάς', 50, 2),
('λεμόνι', 29, 2),
('παρμεζάνα', 431, 9),
('αλάτι', 0, 10),
('πιπέρι', 251, 1),
('σκόρδο σε σκόνη', 149, 1),
('πάπρικα', 282, 1),
('φιλέτα κοτόπουλου', 215, 7),
('αυγά', 155, 8),
('πανσέτα', 336, 7),
('φύλλα σαλάτας', 15, 1),
('ρόκα', 25, 1),
('μανιτάρια', 22, 1),
('φυστίκια', 567, 10),
('μέλι', 304, 2),
('μουστάρδα', 66, 2),
('λάδι ελιάς', 884, 10),
('ξύδι', 18, 2),
('κοτόπουλο (κομμένο σε κυβάκια)', 239, 7),
('κόκκινη πιπεριά', 31, 1),
('κόκκινα φασόλια', 333, 5),
('κονκάσε', 132, 5),
('κονκάσε τηγανητές', 307, 5),
('κονκάσε αποξηραμένες', 569, 5),
('καστανή ζάχαρη', 387, 2),
('κανέλα', 247, 2),
('μελιτζάνες', 25, 1),
('κιμάς μοσχαρίσιος', 250, 6),
('κρόκος κροκομαντήλα', 323, 2),
('μελιτζάνα', 25, 1),
('κιμάς', 30, 6),
('καυτερή σάλτσα', 35, 2),
('τυρί τσένταρ', 30, 4),
('μπαχαρικά', 40, 10),
('κρέμα', 25, 4),
('φρέσκο κόλιανδρο', 35, 1),
('γάλα καρύδας', 40, 4),
('αβοκάντο', 25, 2),
('γιαούρτι', 15, 4),
('μέλι', 30, 4),
('κίτρο', 15, 9),
('αρωματικά μπαχαρικά', 30, 10),
('σοκολάτα', 400, 10),
('καρύδια', 300, 10),
('θαλασσινό αλάτι', 10, 10),
('παγωτό βανίλια', 200, 4);







insert into Recipes (name,description,saltysweet,difficulty,prep_time,cook_time,tip_1,tip_2,tip_3,servings,carbs_per_s,protein_per_s,fat_per_s,cuisine_id,owner_id,group_id)
values ('Κοτόπουλο Πανέ με Παρμεζάνα', 'Φρεσκοψημένo κοτόπουλο στο φούρνο με τραγανή κρούστα και τριμμένη παρμεζάνα.', 1, 3, 20, 25, 'Χρησιμοποιήστε φρέσκο κοτόπουλο για πιο έντονη γεύση.', 'Προσθέστε λίγο αρωματικό μείγμα μπαχαρικών στην κρούστα για περισσότερη πολυπλοκότητα γεύσης.', 'Σερβίρετε με φρέσκο λεμόνι για να ισορροπήσετε την γεύση.', 2, 40, 15, 25, 1, 40, 1),
('Σαλάτα με πανσέτα και φυστίκι', 'Φρέσκη σαλάτα με πανσέτα, ρόκα, καρύδια και ντρέσινγκ βινεγκρέτ.', 1, 2, 15, 0, 'Προσθέστε φρέσκα φύλλα βασιλικού για περισσότερη φρεσκάδα.', 'Προσθέστε λίγο μέλι στο ντρέσινγκ για γλυκιά αντίθεση.', 'Σερβίρετε με φρέσκο ψωμί για πλούσια γεύση.', 3, 30, 15, 35, 2, 54, 1),
('Πικάντικο Τσίλι Κοτόπουλο', 'Κοτόπουλο με σάλτσα τσίλι, σερβίρεται με καυτερό ρύζι και λαχανικά.', 1, 3, 20, 25, 'Προσθέστε φρέσκια κόκκινα πιπεριά για αντίθεση στην πικάντικη γεύση.', 'Χρησιμοποιήστε φρέσκο κοτόπουλο για την καλύτερη γεύση.', 'Σερβίρετε με φρέσκο κομμένο κρεμμύδι και κόλιανδρο για πλούσια γεύση.', 3, 30, 25, 45, 3, 31, 2), 
('Μουσακάς', 'Παραδοσιακή ελληνική συνταγή με φύλλα μουσακά, μελιτζάνες, κιμά και μπεσαμέλ.', 1, 3, 40, 80, 'Σερβίρετε με φρέσκο κομμένο μαύρο πιπέρι για πλούσια γεύση.', 'Χρησιμοποιήστε ελληνικό γιαούρτι για πλούσια και κρεμώδη μπεσαμέλ.', 'Αφήστε τον μουσακά να ξεκουραστεί για λίγα λεπτά πριν το κόψετε για καλύτερη κοπή.', 6, 50, 70, 25, 4, 55, 2),
('Καρυκευμένο Κοτόπουλο με Ρύζι Τζαμαϊκανής Παραδοσιακής Μαγειρικής', 'Κοτόπουλο σε μείγμα καρυκευμάτων, σερβίρεται με αρωματισμένο ρύζι με φρούτα.', 1, 3, 25, 40, 'Προσθέστε φρέσκο δυόσμο για ακόμα περισσότερη φρεσκάδα.', 'Προσθέστε καρύδια και ανανά στο ρύζι για αντίθεση στη γεύση.', 'Σερβίρετε με φρέσκο κομμένο λεμόνι για αναζωογόνηση της γεύσης.', 5, 45, 30, 40, 5, 42, 4),
('Κοτόπουλο Μελιτζάνας με Φέτα', 'Κοτόπουλο με στρώσεις μελιτζάνας και φέτας, ψημένο στο φούρνο για μια γευστική συνταγή.', 1, 3, 25, 45, 'Σερβίρετε με φρέσκα βότανα για περισσότερη γεύση.', 'Προσθέστε λίγο λεμόνι στη σάλτσα για αναζωογόνηση της γεύσης.', 'Αφήστε να ξεκουραστεί η συνταγή για λίγο πριν το σερβίρισμα για να διατηρηθεί η υφή.', 3, 50, 45, 60, 6, 20, 2),
('Μακαρόνια Μεξικάνικα', 'Καυτερά μακαρόνια με κιμά, πιπεριές και καυτερή σάλτσα, διακοσμημένα με τυρί τσένταρ.', 1, 3, 20, 30, 'Προσθέστε φρέσκο κομμένο κολιάντρο για ακόμα περισσότερη γεύση.', 'Χρησιμοποιήστε πικάντικη salsa για ένα εντυπωσιακό αποτέλεσμα.', 'Σερβίρετε με φρέσκο γιαούρτι για να ισορροπήσετε την πικάντικη γεύση.', 2, 35, 20, 30, 7, 13, 3),
('Κοτόπουλο Κάρυ', 'Παραδοσιακό κοτόπουλο κάρυ με αρωματικά μπαχαρικά και κρεμώδη σάλτσα.', 1, 3, 20, 40, 'Προσθέστε φρέσκο κόλιανδρο για περισσότερη φρεσκάδα.', 'Προσθέστε λίγο γάλα καρύδας για ενισχυμένη γεύση.', 'Σερβίρετε με φρέσκο κομμένο αβοκάντο για πλούσια γεύση.', 5, 40, 25, 35, 8, 50, 1),
('Κοτόπουλο με Γιαούρτι και Κίτρο', 'Κοτόπουλο με γιαούρτι, μέλι, κίτρο και αρωματικά μπαχαρικά, ψημένο στο φούρνο.', 1, 2, 15, 30, 'Προσθέστε λίγο κόλιανδρο και μέλι για πλούσια γεύση.', 'Χρησιμοποιήστε φρέσκο κοτόπουλο για την καλύτερη γεύση.', 'Σερβίρετε με φρέσκα λεμόνια και βασιλικό για να διατηρηθεί η φρεσκάδα.', 4, 30, 15, 30, 9, 57, 3),
('Κοτόπουλο με πάπρικα', 'Κοτόπουλο με πικάντικη σάλτσα πάπρικας, σερβίρεται με ρύζι και πράσινα φασολάκια.', 1, 2, 20, 30, 'Προσθέστε φρέσκο κρεμμύδι και σκόρδο για πλούσια γεύση.', 'Προσθέστε λίγο νερό για να διατηρηθεί η υγρασία του κοτόπουλου.', 'Σερβίρετε με φρέσκο κομμένο κολιάντρο για πλούσια γεύση.', 5, 30, 20, 30, 10, 8, 5),
('Σοκολατένια Μπράουνι', 'Πλούσια και κολλώδη μπράουνι σοκολάτας φτιαγμένα με κομματάκια σκούρας σοκολάτας και καρύδια.', 0, 2, 20, 30, 'Προσθέστε μια πρέζα θαλασσινό αλάτι για να ενισχυθεί η γεύση της σοκολάτας.', 'Σερβίρετε ζεστό με μία σταγόνα παγωτό βανίλια για ένα απολαυστικό έδεσμα.', 'Προσθέστε επιπλέον ψιλοκομμένα καρύδια για προσθήκη υφής.', 6, 10, 40, 35, 11, 54, 6),
('Σαλάτα Καπρέζε', 'Φρέσκια και ζωντανή σαλάτα με ώριμες ντομάτες, μοτσαρέλα βουβαλίσια, φύλλα βασιλικού και κρέμα βαλσάμικου.', 1, 1, 10, 15, 'Χρησιμοποιήστε τις πιο ώριμες ντομάτες που μπορείτε να βρείτε για την καλύτερη γεύση.', 'Ρίξτε λίγο παρθένο ελαιόλαδο πάνω από τη σαλάτα λίγο πριν σερβίρετε.', 'Στολίστε με φρέσκο τριμμένο μαύρο πιπέρι για πρόσθετο αίσθημα.', 5, 10, 15, 10, 12, 40, 9),
('Τιραμισού', 'Κλασικό ιταλικό γλυκό με στρώσεις μπισκότων βουτηγμένων σε καφέ, τυρί μασκαρπόνε, και κακάο.', 0, 3, 45, 60, 'Ανακατέψτε γενναιόδωρα το κακάο μεταξύ των στρωμάτων για έντονη σοκολάτα.', 'Αφήστε το τιραμισού να κρυώσει πλήρως πριν το σερβίρετε για να διατηρήσετε τη δομή.', 'Σερβίρετε ψυχρό με προσθήκη τριμμένης σοκολάτας πάνω.', 8, 25, 30, 10, 13, 4, 3),
('Πίτσα Μαργαρίτα', 'Παραδοσιακή ιταλική πίτσα με ντομάτες San Marzano, φρέσκια μοτσαρέλα, φύλλα βασιλικού, και λίγο ελαιόλαδο.', 1, 2, 15, 20, 'Χρησιμοποιήστε φρέσκα φύλλα βασιλικού για την καλύτερη αρωματική εμπειρία.', 'Ζεστάνετε το φούρνο στους υψηλότερους δυνατούς βαθμούς για τραγανή κρούστα.', 'Τελειώστε με λίγο παρθένο ελαιόλαδο πριν το σερβίρετε.', 8, 30, 15, 20, 14, 47, 1),
('Μηλόπιτα', 'Ζεστή και παρηγορητική, επιδόρπιο με τρυφερά μήλα, κανέλα, και βάση μπισκότου.', 0, 2, 50, 40, 'Προσθέστε κάποια ψιλοκομμένα καρύδια όπως πεκάν ή αμύγδαλα για επιπλέον υφή.', 'Σερβίρετε με μια κουταλιά κρέμα ή μια στρώση παγωτό βανίλια.', 'Ρίξτε καραμελωμένη σάλτσα πάνω για επιπλέον γλύκα.', 10, 40, 25, 5, 15, 1, 4),
('Σαλάτα Καίσαρα', 'Κλασική σαλάτα με τραγανά φύλλα ρομανίας, κρουτόν, τυρί παρμεζάνα, και κρεμώδη σάλτσα Καίσαρα.', 1, 1, 10, 0, 'Φτιάξτε τα δικά σας κρουτόν, αφού απλώς προσθέσετε κομμάτια ψωμί σε ελαιόλαδο και σκόρδο πριν τα ψήσετε μέχρι να ροδίσουν.', 'Προσθέστε τριμμένη παρμεζάνα πάνω από τη σαλάτα πριν τη σερβίρετε για την καλύτερη γεύση.', 'Προσθέστε ψημένο κοτόπουλο ή γαρίδες για πρωτεΐνη.', 2, 15, 10, 10, 16, 8, 3),
('Μπανόφι', 'Επιδόρπιο απόλαυσης με βουτυράτη βάση μπισκότου, γέμιση καραμέλας, φέτες μήλου, σαντιγί και τριμμένη σοκολάτα.', 0, 3, 25, 0, 'Βεβαιωθείτε ότι η καραμέλα κρυώνει πλήρως πριν συναρμολογήσετε την πίτα για να αποφευχθεί η ρευστή υφή.', 'Χρησιμοποιήστε ώριμα αλλά σταθερά μήλα για την καλύτερη υφή.', 'Στολίστε με επιπλέον τριμμένη σοκολάτα και πάνω από τη σκόνη κακάο.', 5, 30, 35, 5, 17, 5, 4),
('Ριζότο με Μανιτάρια', 'Κρεμώδες και γευστικό ριζότο με ρύζι Arborio, μανιτάρια, κρεμμύδια, σκόρδο και παρμεζάνα.', 1, 3, 25, 30, 'Χρησιμοποιήστε μια μίξη αγριομανίταρων και καλλιεργημένων μανιταριών για ποικιλία γεύσεων και υφών.', 'Ανακατέψτε ένα κομμάτι βούτυρο και επιπλέον παρμεζάνα στο τέλος για επιπλέον πλούσια γεύση.', 'Στολίστε με φρέσκο μαϊντανό και ρίξτε λίγο έλαιο τρούφας, αν επιθυμείτε.', 4, 40, 20, 15, 18, 20, 1),
('Λεμονόταρτα', 'Τραγανές και γλυκιές λεμονόταρτες με βουτυράτη βάση μπισκότου και ένα ζωηρό γέμιση λεμόνι, που πασπαλίζεται με ζάχαρη άχνη.', 0, 2, 20, 35, 'Προσθέστε το ξύσμα του λεμονιού τόσο στη βάση όσο και στο γέμισμα για επιπλέον γεύση λεμονιού.', 'Αφήστε τις τάρτες να κρυώσουν πλήρως πριν τις κόψετε για να εξασφαλίσετε καθαρά άκρα.', 'Σερβίρετε ψυχρές ή σε θερμοκρασία δωματίου για την καλύτερη υφή.', 8, 30, 20, 5, 19, 57, 9),
('Πίτα με Σπανάκι και Φέτα', 'Αλμυρή πίτα γεμάτη με σοταρισμένο σπανάκι, κρεμμύδια, σκόρδο, κρεμμώδη φέτα και αυγά, ψημένη σε πίτα.', 1, 3, 30, 45, 'Χρησιμοποιήστε φρέσκο σπανάκι και στείλτε κάθε περίσσεια υγρασίας μετά το σοτάρισμα για να αποφύγετε μια μαλακή πίτα.', 'Αισθανθείτε ελεύθεροι να προσθέσετε άλλα λαχανικά όπως μανιτάρια ή πιπεριές για επιπλέον γεύση και θρεπτικά συστατικά.', 'Αφήστε την πίτα να ξεκουραστεί για τουλάχιστον 10 λεπτά πριν την κόψετε για να στερεωθεί.', 5, 30, 35, 15, 20, 34, 3),
('Φρουτοσαλάτα', 'Φρέσκα φρούτα κομμένα σε κυβάκια, όπως φράουλες, αχλάδια, μήλα και ανανάς, με λίγο χυμό λεμονιού και μέλι.', 0, 1, 10, 5, 'Προσθέστε λίγο φρέσκο μαϊντανό για προσθήκη φρεσκάδας.', 'Σερβίρετε με γιαούρτι για περισσότερη γεύση και πρωτεΐνη.', 'Σερβίρετε ψυχρό για την καλύτερη αίσθηση δροσιάς.', 1, 20, 5, 2, 21, 57, 2),
('Πατάτες Οβεν', 'Τραγανές πατάτες φούρνου με ελαιόλαδο, θυμάρι και αλάτι.', 1, 1, 15, 40, 'Προσθέστε λίγη πάπρικα για προσθήκη γεύσης.', 'Σερβίρετε με τζατζίκι ή κέτσαπ.', 'Ψήστε μέχρι να γίνουν χρυσαφί και τραγανές.', 6, 25, 15, 5, 1, 12, 1),
('Πανακότα', 'Γλυκιά συνταγή από την Κρήτη με αμυγδαλόκρεμα και σιρόπι.', 0, 3, 40, 60, 'Δοκιμάστε να προσθέσετε λίγο κανέλα στο σιρόπι για προσθήκη αρωμάτων.', 'Αφήστε την πανακότα να απορροφήσει καλά το σιρόπι πριν τη σερβίρετε.', 'Σερβίρετε σε μικρά κομμάτια με αφρόγαλα ή παγωτό.', 6, 30, 25, 10, 2, 38, 9),
('Γεμιστά Τοματίνια', 'Τοματίνια γεμιστά με κρέμα τυριού, βασιλικό και αλάτι.', 1, 1, 5, 10, 'Προσθέστε λίγο βαλσάμικο για προσθήκη αίσθησης γλύκας.', 'Σερβίρετε με λίγο πιπέρι για προσθήκη απόδοσης.', 'Ψήστε μέχρι να ζεσταθούν και να μαλακώσουν τα τοματίνια.', 1, 20, 15, 5, 3, 4, 2),
('Τάρτα Φράουλας', 'Φρέσκες φράουλες σε τάρτα με λεπτή βάση, γεμιστή με κρέμα πατισερί', 0, 2, 25, 45, 'Δοκιμάστε να προσθέσετε λίγο ζελέ φράουλας για ακόμη περισσότερη γεύση.', 'Σερβίρετε με μια ανάσα σαντιγί ή παγωτό.', 'Ψήστε μέχρι να γίνει η βάση χρυσή και η γέμιση να σφίξει.', 5, 35, 20, 5, 4, 27, 1),
('Σούπα Κοτόσουπα', 'Θερμική και τροφοδοτική σούπα με κοτόσουπα, κοκκινιστή με λάδι, κρεμμύδια, σέλινο και καρότα.', 1, 2, 20, 30, 'Προσθέστε λίγο μαγιάτικο σιρόπι για προσθήκη αρωμάτων.', 'Σερβίρετε με φρέσκο ψωμί και τυρί.', 'Βράστε μέχρι τα λαχανικά να μαλακώσουν και η σούπα να αρχίσει να ενοποιείται.', 5, 15, 10, 10, 5, 58, 2),
('Κρέπες με Σοκολάτα', 'Ζεστές και αφράτες κρέπες γεμιστές με κομμάτια σοκολάτας και πουτίγκα.', 0, 2, 15, 30, 'Προσθέστε λίγο κακάο στη ζύμη για προσθήκη γεύσης.', 'Σερβίρετε με λίγο παγωτό και φρέσκα φρούτα.', 'Ρίξτε λίγο νερό όσο οι κρέπες αρχίζουν να ροδίζουν.', 4, 40, 25, 10, 6, 33, 3),
('Μπουγάτσα', 'Γευστική γεμιστή μπουγάτσα με ζύμη φύλλου και γέμιση από τυρί φέτα.', 1, 3, 30, 60, 'Δοκιμάστε να προσθέσετε λίγο μέλι στην επιφάνεια για ακόμα περισσότερη γεύση.', 'Σερβίρετε με λίγο τζατζίκι ή ντομάτα.', 'Ψήστε μέχρι να γίνει η μπουγάτσα χρυσή και το τυρί να λιώσει.', 4, 25, 30, 15, 7, 46, 4),
('Πέννες Αλφρέντο', 'Πέννες μακαρόνια με κρέμα αλφρέντο, κομμάτια μπέικον και παρμεζάνα.', 1, 2, 20, 25, 'Προσθέστε λίγο φρέσκο βασιλικό για προσθήκη αρωμάτων.', 'Ρίξτε περισσότερη παρμεζάνα από πάνω για προσθήκη γεύσης.', 'Σερβίρετε με φρέσκο τριμμένο πιπέρι.', 4, 30, 25, 15, 8, 46, 9),
('Τσιζκέικ με Μπλεμπέρι', 'Γευστική τσιζκέικ με βάση μπισκότου και γέμιση από μπλεμπέρι.', 0, 3, 40, 50, 'Προσθέστε λίγο τρίμα λεμόνι στο μπλεμπέρι για ακόμη περισσότερη φρεσκάδα.', 'Αφήστε το τσιζκέικ να κρυώσει πλήρως πριν το κόψετε.', 'Σερβίρετε με φρέσκες μπλεμπέρι για διακόσμηση.', 8, 20, 30, 20, 9, 3, 4),
('Μουσακάς Ελληνικός', 'Κλασικό ελληνικό φαγητό με στρώσεις μελιτζάνας, κιμά, πατάτες και μπεσαμέλ.', 1, 3, 40, 60, 'Προσθέστε λίγο κανέλα στον κιμά για ακόμη περισσότερη γεύση.', 'Αφήστε τον μουσακά να ξεκουραστεί πριν το κόψετε για να στερεωθεί.', 'Σερβίρετε με φρέσκο θυμάρι για διακόσμηση.', 6, 35, 25, 15, 10, 10, 1),
('Ταρτάκια Λεμόνι', 'Λαχταριστά μικρά ταρτάκια με λεμονόκρεμα και μαρέγκα.', 0, 2, 25, 35, 'Προσθέστε λίγο λεμόνι για ακόμη περισσότερη γεύση.', 'Σερβίρετε με ένα λεπτό φύλλο μαρέγκας πάνω.', 'Ψήστε μέχρι να γίνουν χρυσαφί και η γέμιση να σφίξει.', 4, 30, 20, 10, 11, 24, 9),
('Κεφτεδάκια', 'Κοκκινιστά κεφτεδάκια με μοσχαρίσιο κιμά, κρεμμύδια και σάλτσα ντομάτας.', 1, 2, 30, 40, 'Προσθέστε λίγο φρέσκο μαϊντανό στην κρέμα για προσθήκη αρωμάτων.', 'Σερβίρετε με ρύζι ή πουρέ πατάτας.', 'Σερβίρετε με ένα φύλλο μαϊντανού για διακόσμηση.', 8, 25, 20, 15, 12, 31, 1),
('Παγωτό Βανίλια', 'Κλασικό παγωτό με γεύση βανίλιας, φτιαγμένο με φρέσκο γάλα και κρέμα.', 0, 1, 15, 0, 'Αφήστε τη ζύμη να κρυώσει πλήρως πριν την παγώσετε.', 'Σερβίρετε με φρέσκα φρούτα ή σιρόπι.', 'Ψήστε μέχρι να πήξει και να γίνει κρεμώδες.', 6, 20, 15, 10, 13, 30, 8),
('Τυρόπιτα', 'Τραγανή σφολιάτα με γέμιση από φέτα και ρίγανη.', 1, 2, 35, 50, 'Προσθέστε λίγο φρέσκο θυμάρι στη γέμιση για προσθήκη αρωμάτων.', 'Σερβίρετε με φρέσκο καλαμπόκι ή σαλάτα.', 'Ψήστε μέχρι η πίτα να γίνει χρυσαφί και ο τυρός να λιώσει.', 4, 25, 20, 15, 14, 29, 8),
('Κεφτέδες Λαχανικών', 'Αφράτοι και υγιεινοί κεφτέδες από χοντροκομμένα λαχανικά, αλεύρι και αυγά.', 1, 2, 25, 30, 'Προσθέστε λίγο πικάντικο κόκκινο πιπέρι για προσθήκη γεύσης.', 'Σερβίρετε με σάλτσα γιαουρτιού ή τζατζίκι.', 'Ψήστε μέχρι να γίνουν χρυσαφί και να σφίξουν.', 8, 20, 10, 30, 15, 7, 10),
('Μπισκότα Σοκολάτας', 'Μαλακά και αφράτα μπισκότα με κομματάκια σοκολάτας.', 0, 2, 15, 20, 'Προσθέστε λίγα καρύδια ή αμύγδαλα για προσθήκη υφής.', 'Σερβίρετε με ένα ποτήρι φρέσκο γάλα.', 'Ψήστε μέχρι να πήξουν και να αρχίσουν να ροδίζουν.', 6, 25, 10, 5, 16, 33, 5),
('Πιπεριές Γεμιστές', 'Φρέσκες πιπεριές γεμιστές με μείγμα ρυζιού, κιμά και τυρί φέτα.', 1, 3, 40, 50, 'Προσθέστε λίγο κινόα για προσθήκη πρωτεΐνης.', 'Σερβίρετε με φρέσκο τζατζίκι ή ντομάτα.', 'Ψήστε μέχρι οι πιπεριές να μαλακώσουν και το τυρί να λιώσει.', 3, 30, 25, 10, 17, 3, 2),
('Κοτόπουλο Σουβλάκι', 'Κομματάκια κοτόπουλου σε ξύλινο ξυλάκι με σως τζατζίκι και ταχίνι.', 1, 2, 20, 30, 'Προσθέστε λίγο χυμό λεμονιού για προσθήκη φρεσκάδας.', 'Σερβίρετε με φρέσκο ψωμί πίτας και χούμους.', 'Ψήστε μέχρι το κοτόπουλο να ψηθεί και να γίνει χρυσαφί.', 6, 25, 15, 20, 18, 29, 9),
('Κανταΐφι', 'Αφράτο κανταΐφι με γέμιση από καρύδια και σιρόπι.', 0, 3, 45, 60, 'Προσθέστε λίγο κανέλα στη γέμιση για ακόμη περισσότερη γεύση.', 'Σερβίρετε με λίγο γιαούρτι ή παγωτό.', 'Ψήστε μέχρι να γίνει το κανταΐφι χρυσαφί και να απορροφήσει το σιρόπι.', 6, 40, 30, 10, 19, 33, 5),
('Σολομός Σουβλάκι με Μανιτάρια Πορσελάνης', 'Φιλέτο σολομού εναλλασσόμενο με μανιτάρια πορσελάνης, σε ραβασάκια, με σάλτσα λεμονιού και καπνιστό αλάτι.', 1, 4, 40, 50, 'Προσθέστε λίγο λευκό κρασί στη σάλτσα για ακόμη περισσότερη γεύση.', 'Σερβίρετε με συνοδευτικό ρύζι μπασμάτι ή πιλάφι.', 'Ψήστε μέχρι ο σολομός να ψηθεί και να αποκτήσει χρυσαφί χρώμα.', 3, 10, 15, 30, 20, 13, 1),
('Ριζότο με Σάφραν και Λεμονοτσούκνιδο', 'Ριζότο με αρωματικό σάφραν, φρέσκο λεμονοτσούκνιδο και παρμεζάνα.', 1, 4, 35, 40, 'Προσθέστε λίγο λευκό κρασί κατά το βράσιμο του ρυζιού για προσθήκη γεύσης.', 'Σερβίρετε με λεπτές φέτες λεμονιού και εξτρα παρμεζάνα.', 'Ανακατέψτε συχνά κατά την προσθήκη του υγρού για ομοιόμορφο βράσιμο.', 2, 30, 20, 10, 21, 22, 9),
('Στιφάδο Αρνί', 'Ζουμερά κομμάτια αρνί με κρεμμυδένια σάλτσα, κόκκινο κρασί και αρωματικά.', 1, 5, 50, 60, 'Προσθέστε λίγη κανέλα για προσθήκη αρωμάτων.', 'Σερβίρετε με πουρέ πατάτας ή ριζότο.', 'Ψήστε μέχρι το κρέας να είναι μαλακό και να ξεκολλάει από τα οστά.', 8, 25, 30, 40, 1, 53, 3),
('Σοκολατένιο Αφράτο Κέικ με Φρούτα του Δάσους', 'Κέικ σοκολάτας με εσωτερική γέμιση από φρέσκα φρούτα του δάσους και σαντιγί.', 0, 4, 45, 55, 'Προσθέστε λίγη βανίλια στη σαντιγί για ακόμη περισσότερη γεύση.', 'Σερβίρετε με σιρόπι σοκολάτας και μερίδα παγωτό.', 'Ψήστε μέχρι να ανέβουν και να ελαφρύνουν.', 10, 35, 40, 20, 2, 33, 5),
('Γκούφρος με Φρέσκα Θαλασσινά', 'Αφράτος γκούφρος με φρέσκα θαλασσινά, μπέικον, φρέσκα λαχανικά και σάλτσα λευκού κρασιού.', 1, 5, 60, 70, 'Προσθέστε λίγη τρούφα για προσθήκη γεύσης και αρώματος.', 'Σερβίρετε με ένα παγωμένο λευκό κρασί.', 'Ψήστε μέχρι ο γκούφρος να είναι τραγανός και οι θαλασσινοί να είναι ψημένοι.', 6, 30, 35, 25, 3, 46, 7),
('Φιλέτο Βραστό Κριθαράκι', 'Σοτέ μακαρόνια με τρυφερό φιλέτο κοτόπουλου, πράσινα αρωματικά λαχανικά και σάλτσα Λεμονάτα.', 1, 4, 45, 55, 'Προσθέστε λίγο φρέσκο δυόσμο για προσθήκη αρωμάτων.', 'Σερβίρετε με φέτες λεμονιού και φρέσκο θυμάρι.', 'Βράστε το κριθαράκι μέχρι να γίνει αφράτο και τρυφερό.', 8, 20, 15, 25, 4, 1, 5),
('Ραβασάκια με Κολοκύθα και Ρίγανη', 'Φυστικοβούτυρο και ταλιατέλες με τρυφερή κολοκύθα, ελαιόλαδο, ρίγανη και παρμεζάνα.', 1, 4, 35, 45, 'Προσθέστε λίγο πιπέρι αν θέλετε εναλλακτική πιπεριά.', 'Σερβίρετε με φρέσκο λεμόνι και παρμεζάνα.', 'Βράστε τις ταλιατέλες μέχρι να γίνουν αφράτες και η κολοκύθα να μαλακώσει.', 2, 25, 20, 30, 5, 36, 3),
('Φιλέτο Μοσχάρι Ροστί', 'Μοσχάρι βρασμένο στον φούρνο με ελαιόλαδο, σκόρδο και δεντρολίβανο.', 1, 5, 50, 60, 'Προσθέστε λίγο κρασί κατά το ψήσιμο για προσθήκη αρωμάτων.', 'Σερβίρετε με μαρούλι και πουρέ πατάτας.', 'Ψήστε μέχρι το φιλέτο να είναι χρυσαφί και τρυφερό.', 4, 20, 30, 40, 6, 22, 3),
('Καραμελωμένα Πεπερόνι με Φέτα και Μέλι', 'Πεπερόνι καραμελωμένα με μέλι και τριμμένη φέτα.', 1, 4, 30, 40, 'Προσθέστε λίγη φλούδα λεμονιού για προσθήκη αρωμάτων.', 'Σερβίρετε με φρέσκο θυμάρι και κριθαράκι.', 'Ψήστε μέχρι τα πεπερόνι να μαλακώσουν και το τυρί να λιώσει.', 5, 20, 25, 15, 7, 29, 1),
('Μπριός Στήθος Κοτόπουλο με Φρέσκο Ροκφόρ', 'Μοσχαρίσιο μπριός στήθος κοτόπουλου γεμιστό με φρέσκο ροκφόρ και περιχυμένο με σάλτσα λευκού κρασιού.', 1, 5, 55, 65, 'Προσθέστε λίγο αποξηραμένο θυμάρι κατά το ψήσιμο για προσθήκη αρωμάτων.', 'Σερβίρετε με συνοδευτικό ριζότο ή πουρέ πατάτας.', 'Ψήστε μέχρι το κοτόπουλο να ψηθεί και να αποκτήσει χρυσαφί χρώμα.', 1, 25, 20, 35, 8, 23, 2),
('Μπριός Μοσχαρίσιο με Σάλτσα Μαύρης Τρούφας', 'Φιλέτο μοσχαρίσιο μπριός με περιχύσεις από σάλτσα μαύρης τρούφας και συνοδευτικό πουρέ πατάτας με κρέμα.', 1, 5, 60, 70, 'Προσθέστε λίγο άσπρο κρασί κατά το ψήσιμο για προσθήκη αρωμάτων.', 'Σερβίρετε με φρέσκα βοτάνια όπως θυμάρι και δυόσμο.', 'Ψήστε μέχρι το μπριός να είναι τρυφερό και να απορροφήσει τις γεύσεις.', 4, 30, 35, 45, 9, 49, 2),
('Σουφλέ Λαχανικών με Παρμεζάνα και Φρέσκα Βότανα', 'Αφράτο σουφλέ με λαχανικά, τριμμένη παρμεζάνα και φρέσκα βότανα όπως βασιλικό και δυόσμο.', 1, 4, 50, 60, 'Προσθέστε λίγο φρέσκο σκόρδο για προσθήκη αρωμάτων.', 'Σερβίρετε με πράσινη σαλάτα και ντιπ από κρέμα τυριού.', 'Ψήστε μέχρι το σουφλέ να φουσκώσει και να αποκτήσει χρυσαφί χρώμα.', 3, 25, 30, 20, 10, 33, 3),
('Παϊδάκια Μοσχαρίσια με Μέλι και Κίτρο', 'Παϊδάκια μοσχαρίσια σε πεντανόστιμη σάλτσα με μέλι, κίτρο και αρωματικά.', 1, 4, 40, 50, 'Προσθέστε λίγο κανέλα κατά το ψήσιμο για προσθήκη γεύσης.', 'Σερβίρετε με φρέσκο κομμάτι λεμονιού και πατάτες τηγανητές.', 'Ψήστε μέχρι τα παϊδάκια να είναι τρυφερά και να απορροφήσουν τις γεύσεις.', 7, 35, 30, 40, 11, 44, 3),
('Σούπα Σπαραγγιών με Καρύδα και Λεμονοτζίντζερ', 'Αρωματική σούπα σπαραγγιών με κρέμα καρύδας και λεμονοτζίντζερ για φρεσκάδα και γεύση.', 1, 3, 35, 45, 'Προσθέστε λίγο πιπέρι για πιο έντονη γεύση.', 'Σερβίρετε με φρέσκα φύλλα μέντας και φέτες λεμονιού.', 'Βράστε μέχρι οι σπαράγγια να μαλακώσουν και η σούπα να πυκνωθεί ελαφρώς.', 4, 20, 15, 10, 12, 45, 3),
('Γαλοπούλα Φούρνου με Ροζ Πιπέρι και Λεμονόχορτο', 'Φιλέτο γαλοπούλας σε αρωματική μαρινάδα με ροζ πιπέρι, λεμονόχορτο και μέλι.', 1, 4, 45, 55, 'Προσθέστε λίγο χυμό λάιμ ή πορτοκάλι για προσθήκη φρεσκάδας.', 'Σερβίρετε με συνοδευτικό ρύζι με λεμόνι και αρωματικά λαχανικά.', 'Ψήστε μέχρι η γαλοπούλα να είναι χρυσαφί και τρυφερή.', 4, 15, 10, 20, 13, 3, 7);

insert into steps (step_order, step_instr, recipe_id)
values (1, 'Προθερμαίνετε το φούρνο στους 200°C.', 1),
(2, 'Ετοιμάστε τρία μπολ: Στο πρώτο, βάλτε το αλεύρι. Στο δεύτερο, τα χτυπημένα αυγά. Στο τρίτο, την τριμμένη παρμεζάνα, το ψωμί τριμμένο, το αλάτι, το πιπέρι, το σκόρδο σε σκόνη και την πάπρικα.', 1),
(3, 'Περάστε τα φιλέτα κοτόπουλου από το αλεύρι, τα αυγά και το μείγμα παρμεζάνας και ψωμιού, πιέζοντας καλά να κολλήσει.', 1),
(4, 'Ζεστάνετε το ελαιόλαδο σε ένα τηγάνι και τηγανίστε τα φιλέτα μέχρι να ροδίσουν, περίπου 3 λεπτά από κάθε πλευρά.', 1),
(5, 'Μεταφέρετε τα φιλέτα σε ένα ταψί και ψήστε στο φούρνο για 20-25 λεπτά ή μέχρι να είναι πλήρως μαγειρεμένα.', 1),
(6, 'Σερβίρετε με φρέσκο λεμόνι για να ισορροπήσετε τη γεύση.', 1),
(1, 'Σε ένα τηγάνι, τηγανίστε την πανσέτα μέχρι να γίνει τραγανή. Αφήστε τη να στραγγίξει σε χαρτί κουζίνας.', 2),
(2, 'Σε ένα μεγάλο μπολ, ανακατέψτε τη ρόκα, τα καρύδια, τα φυστίκια και την πανσέτα.', 2),
(3, 'Προετοιμάστε το ντρέσινγκ ανακατεύοντας το λάδι, τον ξίδι, το μουστάρδα, το μέλι, το αλάτι και το πιπέρι.', 2),
(4, 'Ανακατέψτε το ντρέσινγκ με τη σαλάτα και σερβίρετε παγωμένο.', 2),
(1, 'Σε μια κατάλληλη κατσαρόλα, θερμαίνετε το ελαιόλαδο σε μέτρια φωτιά.', 3),
(2, 'Προσθέστε τα κομμένα κοτόπουλα και ψήστε μέχρι να ροδίσουν, περίπου 5 λεπτά.', 3),
(3, 'Προσθέστε το κρεμμύδι και συνεχίστε το μαγείρεμα μέχρι να μαλακώσει.', 3),
(4, 'Προσθέστε το σκόρδο και την πάπρικα και μαγειρέψτε για ένα λεπτό μέχρι να εκπέσει η αρωματική τους γεύση.', 3),
(5, 'Ρίξτε τη σάλτσα τσίλι στην κατσαρόλα και ανακατέψτε καλά.', 3),
(6, 'Προσθέστε το νερό ή τον κόκκο λαχανικών, ανακατέψτε και αφήστε να βράσει.', 3),
(7, 'Αφήστε το τσίλι να βράσει και μειώστε τη φωτιά σε χαμηλή. Αφήστε το να σιγοβράσει για περίπου 15 λεπτά, ανακατεύοντας περιοδικά.', 3),
(8, 'Σερβίρετε το τσίλι κοτόπουλο ζεστό, συνοδευμένο με καυτερό ρύζι και φρέσκα λαχανικά, αν επιθυμείτε.', 3),
(9, 'Διακοσμήστε με φρέσκο κομμένο κρεμμύδι και κόλιανδρο, αν επιθυμείτε.', 3),
(1, 'Αρχικά, ξεκινήστε με την προετοιμασία των φύλλων μουσακά. Αν πρόκειται για φύλλα μουσακά από κατάψυξη, αφήστε τα να αποψυχθούν στην κατάψυξη και στη συνέχεια ψήστε τα στο φούρνο.', 4),
(2, 'Στη συνέχεια, ασχοληθείτε με την προετοιμασία της κρέμας μπεσαμέλ. Λιώστε το βούτυρο σε μια κατσαρόλα και προσθέστε το αλεύρι. Χτυπήστε καλά μέχρι να ενσωματωθεί το αλεύρι με το βούτυρο και να αποκτήσει μια ελαφρώς χρυσαφί απόχρωση.', 4),
(3, 'Σιγοβράστε το μείγμα για μερικά λεπτά, στη συνέχεια αρχίστε να προσθέτετε το γάλα σταδιακά, ανακατεύοντας συνεχώς μέχρι να έχετε μια λεία, πυκνή μπεσαμέλ.', 4),
(4, 'Αφαιρέστε την κατσαρόλα από τη φωτιά και προσθέστε το αυγό, το αλάτι και το πιπέρι, ανακατεύοντας καλά μέχρι να ενσωματωθούν.', 4),
(5, 'Στη συνέχεια, σε ένα μεγάλο ταψί, διατάξτε εναλλακτικά φύλλα μουσακά και κρέμα μπεσαμέλ, αφήνοντας ένα φύλλο μουσακά στο τέλος.', 4),
(6, 'Αφήστε την μουσακά να ξεκουραστεί για λίγο πριν την κόψετε για καλύτερη κοπή.', 4),
(7, 'Σερβίρετε τη μουσακά με ένα δροσερό γιαούρτι.', 4),
(1, 'Αρχικά, προετοιμάστε τα υλικά για το καρυκευμένο κοτόπουλο και το ρύζι Τζαμαϊκανής παραδοσιακής μαγειρικής.', 5),
(2, 'Σε μια κατσαρόλα, θερμάνετε λίγο ελαιόλαδο σε μέτρια φωτιά και προσθέστε τα κομμένα κοτόπουλα. Μαγειρέψτε μέχρι να πάρουν χρώμα.', 5),
(3, 'Προσθέστε τα καρυκεύματα και συνεχίστε το μαγείρεμα για μερικά λεπτά, μέχρι να εκπέσει η αρωματική τους γεύση.', 5),
(4, 'Προσθέστε λίγο νερό και αφήστε το κοτόπουλο να σιγοβράσει μέχρι να μαλακώσει και να ενσωματωθούν τα αρώματα.', 5),
(5, 'Σε έναν δεύτερο τηγάνι, προσθέστε το ρύζι και τον απαραίτητο χυμό από ανανά. Αφήστε το ρύζι να βράσει και να απορροφήσει το υγρό.', 5),
(6, 'Όταν το ρύζι είναι έτοιμο, σερβίρετε το κοτόπουλο πάνω από το ρύζι και διακοσμήστε με φρέσκο δυόσμο.', 5),
(7, 'Σερβίρετε το πιάτο ζεστό και απολαύστε το!', 5),
(1, 'Ετοιμάστε τα υλικά για το κοτόπουλο με μελιτζάνα και φέτα.', 6),
(2, 'Αρχικά, φτιάξτε τις στρώσεις μελιτζάνας και φέτας.', 6),
(3, 'Τοποθετήστε το κοτόπουλο πάνω στις στρώσεις και ψήστε στο φούρνο μέχρι να ψηθεί και να χρυσώσει.', 6),
(4, 'Σερβίρετε με φρέσκα βότανα για περισσότερη γεύση.', 6),
(5, 'Προσθέστε λίγο λεμόνι στη σάλτσα για αναζωογόνηση της γεύσης.', 6),
(6, 'Αφήστε να ξεκουραστεί η συνταγή για λίγο πριν το σερβίρισμα για να διατηρηθεί η υφή.', 6),
(1, 'Προετοιμάστε τα υλικά για τα μακαρόνια Μεξικάνικα.', 7),
(2, 'Βράστε τα μακαρόνια μέχρι να γίνουν αλ dente σύμφωνα με τις οδηγίες στη συσκευασία.', 7),
(3, 'Σε ένα τηγάνι, ψήστε τον κιμά και προσθέστε τις πιπεριές.', 7),
(4, 'Προσθέστε την καυτερή σάλτσα και αφήστε να σιγοβράσει για λίγα λεπτά.', 7),
(5, 'Σερβίρετε τα μακαρόνια με το μείγμα κιμάτων και πιπεριών, πάνω από αυτά ρίξτε τυρί τσένταρ.', 7),
(6, 'Προσθέστε φρέσκο κομμένο κολιάντρο για ακόμα περισσότερη γεύση.', 7),
(7, 'Χρησιμοποιήστε πικάντικη salsa για ένα εντυπωσιακό αποτέλεσμα.', 7),
(8, 'Σερβίρετε με φρέσκο γιαούρτι για να ισορροπήσετε την πικάντικη γεύση.', 7),
(1, 'Αρχικά, προετοιμάστε τα υλικά για το κοτόπουλο κάρυ.', 8),
(2, 'Σε μια κατσαρόλα, θερμάνετε λίγο ελαιόλαδο σε μέτρια φωτιά και προσθέστε τα κομμένα κοτόπουλα. Μαγειρέψτε μέχρι να πάρουν χρώμα.', 8),
(3, 'Προσθέστε την κρέμα και αφήστε το μείγμα να σιγοβράσει για μερικά λεπτά.', 8),
(4, 'Προσθέστε τον κόλιανδρο για περισσότερη φρεσκάδα.', 8),
(5, 'Προσθέστε λίγο γάλα καρύδας για ενισχυμένη γεύση.', 8),
(6, 'Σερβίρετε με φρέσκο κομμένο αβοκάντο για πλούσια γεύση.', 8),
(1, 'Αρχικά, προετοιμάστε τα υλικά για το κοτόπουλο με γιαούρτι και κίτρο.', 9),
(2, 'Ανάμειξε το γιαούρτι, το μέλι, το κίτρο και τα αρωματικά μπαχαρικά.', 9),
(3, 'Αφού ανακατέψετε καλά, προσθέστε το μίγμα στο κοτόπουλο.', 9),
(4, 'Χτυπήστε το κοτόπουλο με το μίγμα μέχρι να είναι καλά επικαλυμμένο.', 9),
(5, 'Ψήστε το κοτόπουλο στο φούρνο για περίπου 30 λεπτά ή μέχρι να ψηθεί πλήρως.', 9),
(1, 'Αρχικά, προετοιμάστε τα υλικά για το κοτόπουλο με πάπρικα.', 10),
(2, 'Σε ένα τηγάνι, θερμάνετε λίγο ελαιόλαδο σε μέτρια φωτιά και προσθέστε το κοτόπουλο.', 10),
(3, 'Ανακατέψτε το κοτόπουλο με την πάπρικα μέχρι να είναι καλά επικαλυμμένο.', 10),
(4, 'Προσθέστε τα κρεμμύδια και το σκόρδο και συνεχίστε το μαγείρεμα μέχρι να μαλακώσουν.', 10),
(5, 'Προσθέστε το νερό και αφήστε το κοτόπουλο να σιγοβράσει μέχρι να μαγειρευτεί πλήρως.', 10),
(6, 'Σερβίρετε το κοτόπουλο με ρύζι και πράσινα φασολάκια.', 10),
(7, 'Στο τέλος, προσθέστε φρέσκο κομμένο κολιάντρο για πλούσια γεύση.', 10),
(1, 'Αρχικά, προετοιμάστε τα υλικά για τα σοκολατένια μπράουνι.', 11),
(2, 'Σε ένα μεγάλο μπολ, ανακατέψτε τη σοκολάτα και τα καρύδια μέχρι να ενσωματωθούν καλά.', 11),
(3, 'Προσθέστε μια πρέζα θαλασσινό αλάτι για να ενισχυθεί η γεύση της σοκολάτας.', 11),
(4, 'Ανακατέψτε καλά και μεταφέρετε το μείγμα σε ένα ταψί.', 11),
(5, 'Ψήστε στον προθερμασμένο φούρνο για περίπου 20 λεπτά.', 11),
(6, 'Σερβίρετε το ζεστό με μία σταγόνα παγωτό βανίλια για ένα απολαυστικό έδεσμα.', 11),
(7, 'Προσθέστε επιπλέον ψιλοκομμένα καρύδια για προσθήκη υφής.', 11),
(1, 'Αρχικά, προετοιμάστε τα υλικά για τη σαλάτα Καπρέζε.', 12),
(2, 'Κόψτε τις ώριμες ντομάτες σε φέτες και τοποθετήστε τις σε ένα πιάτο σερβιρίσματος.', 12),
(3, 'Κόψτε τη μοτσαρέλα βουβαλίσια σε λεπτές φέτες και τοποθετήστε τις πάνω από τις ντομάτες.', 12),
(4, 'Διασκορπίστε φύλλα βασιλικού πάνω από τη μοτσαρέλα.', 12),
(5, 'Ρίξτε λίγο παρθένο ελαιόλαδο πάνω από τη σαλάτα λίγο πριν σερβίρετε.', 12),
(6, 'Στολίστε με φρέσκο τριμμένο μαύρο πιπέρι για πρόσθετο αίσθημα.', 12),
(1, 'Αρχικά, προετοιμάστε τα υλικά για το τιραμισού.', 13),
(2, 'Ετοιμάστε τον καφέ σας και αφήστε το να κρυώσει στην πλευρά.', 13),
(3, 'Ανακατέψτε γενναιόδωρα το κακάο μεταξύ των στρωμάτων για έντονη σοκολάτα.', 13),
(4, 'Σε ένα μεγάλο μπολ, ανακατέψτε τον μασκαρπόνε με μια κουταλιά.', 13),
(5, 'Στρώστε ένα στρώμα μπισκότων σε ένα ταψί.', 13),
(6, 'Σκεπάστε το στρώμα μπισκότων με τον καφέ, αφήνοντας τα μπισκότα να απορροφήσουν το υγρό.', 13),
(7, 'Απλώστε το μίγμα μασκαρπόνε πάνω από το στρώμα μπισκότων.', 13),
(8, 'Συνεχίστε τη διαδικασία για να στρώσετε περισσότερα στρώματα μπισκότων, καφέ και μασκαρπόνε.', 13),
(9, 'Χρησιμοποιήστε τα μπισκότα και το κακάο για τη διακόσμηση της κορυφής του τιραμισού.', 13),
(10, 'Αφήστε το τιραμισού να κρυώσει πλήρως πριν το σερβίρετε για να διατηρήσετε τη δομή.', 13),
(11, 'Σερβίρετε ψυχρό με προσθήκη τριμμένης σοκολάτας πάνω.', 13),
(1, 'Αρχικά, προετοιμάστε τα υλικά για την πίτσα Μαργαρίτα.', 14),
(2, 'Ζεστάνετε το φούρνο στους υψηλότερους δυνατούς βαθμούς για τραγανή κρούστα.', 14),
(3, 'Απλώστε τη ζύμη σε μια ταψί πίτσας.', 14),
(4, 'Απλώστε ομοιόμορφα τη σάλτσα ντομάτας πάνω στη ζύμη.', 14),
(5, 'Προσθέστε τις φρέσκιες φέτες μοτσαρέλας στην πίτσα.', 14),
(6, 'Τοποθετήστε φύλλα βασιλικού σε διάφορα σημεία της πίτσας.', 14),
(7, 'Ψήστε στον προθερμασμένο φούρνο για περίπου 15-20 λεπτά ή μέχρι η ζύμη να γίνει χρυσαφί και η μοτσαρέλα να λιώσει.', 14),
(8, 'Τελειώστε με λίγο παρθένο ελαιόλαδο πριν το σερβίρετε.', 14),
(1, 'Αρχικά, προετοιμάστε τα υλικά για τη μηλόπιτα.', 15),
(2, 'Ανακατέψτε τα τρυφερά μήλα με την κανέλα σε ένα μπολ.', 15),
(3, 'Απλώστε τη βάση μπισκότου σε ένα ταψί.', 15),
(4, 'Απλώστε ομοιόμορφα το μείγμα μήλου και κανέλας πάνω στη βάση.', 15),
(5, 'Ψήστε στον προθερμασμένο φούρνο για περίπου 40-50 λεπτά, μέχρι η βάση να γίνει χρυσαφί και τα μήλα να μαλακώσουν.', 15),
(6, 'Προσθέστε κάποια ψιλοκομμένα καρύδια όπως πεκάν ή αμύγδαλα για επιπλέον υφή.', 15),
(7, 'Σερβίρετε με μια κουταλιά κρέμα ή μια στρώση παγωτό βανίλια.', 15),
(8, 'Ρίξτε καραμελωμένη σάλτσα πάνω για επιπλέον γλύκα.', 15),
(1, 'Αρχικά, πλύνετε και στεγνώστε καλά τα φύλλα ρομανίας.', 16),
(2, 'Κόψτε τα φύλλα ρομανίας σε μεγάλα κομμάτια.', 16),
(3, 'Ετοιμάστε τα κρουτόν είτε ψήνοντάς τα στον φούρνο με λίγο ελαιόλαδο είτε αγοράζοντάς τα έτοιμα.', 16),
(4, 'Τρίψτε φρέσκο τυρί παρμεζάνα.', 16),
(5, 'Σε ένα μπολ, ανακατέψτε την κρεμώδη σάλτσα Καίσαρα με τα φύλλα ρομανίας ώστε να καλυφθούν καλά.', 16),
(6, 'Προσθέστε τα κρουτόν και το τριμμένο τυρί παρμεζάνα στη σαλάτα.', 16),
(7, 'Ανακατέψτε απαλά ώστε τα υλικά να μοιραστούν ομοιόμορφα.', 16),
(8, 'Σερβίρετε αμέσως για να διατηρηθεί η σαλάτα τραγανή.', 16),
(1, 'Αρχικά, προετοιμάστε τα υλικά για το μπανόφι.', 17),
(2, 'Δημιουργήστε μια βάση μπισκότου σε ένα ταψί.', 17),
(3, 'Ανακατέψτε τη γέμιση καραμέλας και τις φέτες μήλου.', 17),
(4, 'Απλώστε τη γέμιση με καραμέλα και μήλο πάνω από τη βάση μπισκότου.', 17),
(5, 'Προσθέστε σαντιγί και τριμμένη σοκολάτα πάνω από τη γέμιση.', 17),
(6, 'Βεβαιωθείτε ότι η καραμέλα κρυώνει πλήρως πριν συναρμολογήσετε την πίτα για να αποφευχθεί η ρευστή υφή.', 17),
(7, 'Χρησιμοποιήστε ώριμα αλλά σταθερά μήλα για την καλύτερη υφή.', 17),
(8, 'Στολίστε με επιπλέον τριμμένη σοκολάτα και πάνω από τη σκόνη κακάο.', 17),
(1, 'Αρχικά, ζεστάνετε ένα κομμάτι βούτυρο σε μια μεγάλη κατσαρόλα σε μέτρια φωτιά.', 18),
(2, 'Προσθέστε τα κρεμμύδια και το σκόρδο και σωτάρετέ τα μέχρι να μαλακώσουν, περίπου 5 λεπτά.', 18),
(3, 'Προσθέστε τα μανιτάρια και συνεχίστε να μαγειρεύετε μέχρι να γίνουν χρυσόκοκκα, περίπου 5 λεπτά ακόμα.', 18),
(4, 'Ρίξτε το ρύζι στην κατσαρόλα και ανακατέψτε καλά μέχρι το ρύζι να απορροφήσει το βούτυρο και να γίνει διαφανές, περίπου 2 λεπτά.', 18),
(5, 'Προσθέστε το κρασί και ανακατέψτε συχνά μέχρι να απορροφηθεί από το ρύζι.', 18),
(6, 'Προσθέστε το ζωμό κουταλιά-κουταλιά και μαγειρέψτε, ανακατεύοντας συχνά, μέχρι το ρύζι να είναι μαλακό αλλά ακόμα ελαφρώς αλδέοντα, περίπου 15-20 λεπτά.', 18),
(7, 'Αφαιρέστε από τη φωτιά και ανακατέψτε το ρίζο στο κρέμα βούτυρου και την επιπλέον παρμεζάνα.', 18),
(8, 'Σερβίρετε το ριζότο ζεστό, στολισμένο με φρέσκο μαϊντανό και με λίγο έλαιο τρούφας αν επιθυμείτε.', 18),
(1, 'Αρχικά, προετοιμάστε τη βάση της τάρτας ανακατεύοντας τα μπισκότα και το βούτυρο σε ένα μπολ.', 19),
(2, 'Πιέστε το μείγμα μπισκότου σε ένα ταψί τάρτας και ισιώστε το με το πίσω μέρος ενός κουταλιού.', 19),
(3, 'Ψήστε τη βάση της τάρτας στον προθερμασμένο φούρνο για περίπου 10 λεπτά μέχρι να χρυσώσει ελαφρώς.', 19),
(4, 'Ενώ η βάση ψήνεται, προετοιμάστε το γέμισμα ανακατεύοντας τον χυμό και το ξύσμα του λεμονιού, τα αυγά, τη ζάχαρη και το αλεύρι σε ένα μεγάλο μπολ.', 19),
(5, 'Αφού η βάση είναι έτοιμη, χαμηλώστε τη θερμοκρασία του φούρνου στους 160°C.', 19),
(6, 'Απλώστε το γέμισμα πάνω στην ψημένη βάση και επιστρέψτε την τάρτα στο φούρνο.', 19),
(7, 'Ψήστε για περίπου 20-25 λεπτά ή μέχρι να πήξει το γέμισμα.', 19),
(8, 'Αφήστε τις τάρτες να κρυώσουν πλήρως πριν τις κόψετε για να εξασφαλίσετε καθαρά άκρα.', 19),
(9, 'Σερβίρετε τις τάρτες ψυχρές ή σε θερμοκρασία δωματίου για την καλύτερη υφή.', 19),
(1, 'Αρχικά, ζεστάνετε το φούρνο στους 180°C και ετοιμάστε το ταψί για ψήσιμο.', 20),
(2, 'Σε ένα μεγάλο τηγάνι, σοτάρετε τα κρεμμύδια και το σκόρδο μέχρι να μαλακώσουν και να αρχίσουν να καραμελώνουν.', 20),
(3, 'Προσθέστε το σπανάκι στο τηγάνι και σοτάρετε μέχρι να μαραθεί και να μαλακώσει.', 20),
(4, 'Αφαιρέστε το μείγμα από τη φωτιά και αφήστε το να κρυώσει ελαφρώς.', 20),
(5, 'Σε ένα μπολ, χτυπήστε τα αυγά και προσθέστε τη φέτα, ανακατεύοντας καλά.', 20),
(6, 'Προσθέστε το σοταρισμένο μείγμα σπανακιού και κρεμμύδι-σκόρδου στο μπολ με τα αυγά και ανακατέψτε καλά.', 20),
(7, 'Απλώστε τη φύλλωση σε ένα ταψί για πίτα και ρίξτε το μείγμα μέσα.', 20),
(8, 'Ψήστε στον προθερμασμένο φούρνο για περίπου 30-35 λεπτά ή μέχρι να τυχόν άκρα γίνουν χρυσαφί.', 20),
(9, 'Αφήστε την πίτα να ξεκουραστεί για τουλάχιστον 10 λεπτά πριν την κόψετε για να στερεωθεί.', 20),
(1, 'Κόψτε τα φρούτα σε κυβάκια και τοποθετήστε τα σε ένα μπολ.', 21),
(2, 'Προσθέστε λίγο χυμό λεμονιού και μέλι πάνω από τα φρούτα και ανακατέψτε καλά.', 21),
(3, 'Προσθέστε λίγο φρέσκο μαϊντανό για προσθήκη φρεσκάδας και ανακατέψτε ξανά.', 21),
(4, 'Σερβίρετε τη φρουτοσαλάτα με γιαούρτι για περισσότερη γεύση και πρωτεΐνη.', 21),
(5, 'Απολαύστε τη φρουτοσαλάτα ψυχρή για την καλύτερη αίσθηση δροσιάς.', 21),
(1, 'Κόψτε τις πατάτες σε κομμάτια και τοποθετήστε τις σε ένα μπολ.', 22),
(2, 'Προσθέστε ελαιόλαδο, θυμάρι και αλάτι στις πατάτες και ανακατέψτε καλά.', 22),
(3, 'Προσθέστε λίγη πάπρικα για προσθήκη γεύσης και ανακατέψτε ξανά.', 22),
(4, 'Προθερμάνετε τον φούρνο στους 200 βαθμούς Κελσίου.', 22),
(5, 'Απλώστε τις πατάτες σε ένα μονό στρώμα σε ένα ταψί.', 22),
(6, 'Ψήστε τις πατάτες στον προθερμασμένο φούρνο για περίπου 25 λεπτά.', 22),
(7, 'Αφαιρέστε το ταψί από το φούρνο και ανακατέψτε τις πατάτες.', 22),
(8, 'Επιστρέψτε το ταψί στο φούρνο και συνεχίστε το ψήσιμο για άλλα 15 λεπτά ή μέχρι να γίνουν χρυσαφί και τραγανές.', 22),
(9, 'Αφαιρέστε τις πατάτες από το φούρνο και αφήστε τις να κρυώσουν για μερικά λεπτά πριν τις σερβίρετε.', 22),
(10, 'Σερβίρετε τις πατάτες οβεν με τζατζίκι ή κέτσαπ.', 22),
(1, 'Αρχικά, προθερμάνετε το φούρνο στους 180 βαθμούς Κελσίου.', 23),
(2, 'Σε ένα μεγάλο μπολ, ανακατέψτε την αμυγδαλόκρεμα μέχρι να γίνει απαλή.', 23),
(3, 'Προσθέστε το σιρόπι στην αμυγδαλόκρεμα και ανακατέψτε καλά.', 23),
(4, 'Προσθέστε λίγη κανέλα στο σιρόπι και ανακατέψτε ξανά για προσθήκη αρωμάτων.', 23),
(5, 'Τοποθετήστε το μείγμα σε ένα ταψί και ομαλοποιήστε την επιφάνεια με ένα κουτάλι.', 23),
(6, 'Ψήστε στον προθερμασμένο φούρνο για περίπου 30 λεπτά ή μέχρι να αποκτήσει χρυσαφί χρώμα στην επιφάνεια.', 23),
(7, 'Αφαιρέστε το ταψί από το φούρνο και αφήστε την πανακότα να κρυώσει πλήρως πριν την κόψετε.', 23),
(8, 'Μετά την κρύωση, κόψτε την πανακότα σε μικρά κομμάτια.', 23),
(9, 'Σερβίρετε την πανακότα με αφρόγαλα ή παγωτό για επιπλέον γεύση και απόλαυση.', 23),
(1, 'Πλύνετε καλά τα τοματίνια και κόψτε το επάνω μέρος τους.', 24),
(2, 'Αφαιρέστε προσεκτικά το εσωτερικό από τα τοματίνια με ένα κουταλάκι.', 24),
(3, 'Σε ένα μπολ, ανακατέψτε την κρέμα τυριού με ψιλοκομμένο βασιλικό και λίγο αλάτι.', 24),
(4, 'Γεμίστε τα τοματίνια με το μείγμα κρέμας τυριού χρησιμοποιώντας ένα μικρό κουταλάκι ή σακούλα ζαχαροπλαστικής.', 24),
(5, 'Βάλτε τα γεμιστά τοματίνια σε μια πιατέλα και σερβίρετε.', 24),
(1, 'Ετοιμάστε τη βάση της τάρτας και ψήστε την σύμφωνα με τις οδηγίες της συνταγής.', 25),
(2, 'Αφήστε τη βάση να κρυώσει εντελώς.', 25),
(3, 'Ετοιμάστε την κρέμα πατισερί και αφήστε την να κρυώσει.', 25),
(4, 'Απλώστε την κρέμα πατισερί ομοιόμορφα πάνω στη βάση της τάρτας.', 25),
(5, 'Πλύνετε και κόψτε τις φράουλες σε φέτες.', 25),
(6, 'Απλώστε τις φράουλες πάνω από την κρέμα πατισερί στη βάση της τάρτας.', 25),
(7, 'Γαρνίρετε με λίγη ζάχαρη άχνη αν θέλετε και σερβίρετε.', 25),
(1, 'Σε μια κατσαρόλα, ζεστάνετε λίγο λάδι σε μέτρια φωτιά.', 26),
(2, 'Προσθέστε ψιλοκομμένα κρεμμύδια, σέλινο και καρότα και σοτάρετε μέχρι να μαλακώσουν.', 26),
(3, 'Προσθέστε κοτόσουπα και αφήστε να βράσει.', 26),
(4, 'Μειώστε τη φωτιά και σιγοβράστε μέχρι τα λαχανικά να μαλακώσουν.', 26),
(5, 'Προσθέστε κομμάτια μαγειρεμένου κοτόπουλου στη σούπα.', 26),
(6, 'Συνεχίστε το σιγοβράσιμο για λίγα λεπτά ακόμα μέχρι να ζεσταθεί καλά το κοτόπουλο.', 26),
(7, 'Σερβίρετε ζεστή με φρεσκοτριμμένο πιπέρι και λίγο ψιλοκομμένο μαϊντανό.', 26),
(1, 'Ετοιμάστε το μείγμα για τις κρέπες και αφήστε το να ξεκουραστεί για 30 λεπτά.', 27),
(2, 'Ζεστάνετε ένα αντικολλητικό τηγάνι σε μέτρια φωτιά.', 27),
(3, 'Ρίξτε μια μικρή ποσότητα μείγματος στο τηγάνι και απλώστε το ομοιόμορφα.', 27),
(4, 'Μαγειρέψτε την κρέπα μέχρι να αρχίσει να ροδίζει από κάτω και αναποδογυρίστε.', 27),
(5, 'Προσθέστε κομμάτια σοκολάτας και λίγο πουτίγκα στη μισή κρέπα.', 27),
(6, 'Διπλώστε την κρέπα στη μέση και μαγειρέψτε για λίγα δευτερόλεπτα μέχρι να λιώσει η σοκολάτα.', 27),
(7, 'Σερβίρετε ζεστές με λίγη ζάχαρη άχνη ή σιρόπι σοκολάτας.', 27),
(1, 'Ετοιμάστε τη ζύμη φύλλου ή χρησιμοποιήστε έτοιμη ζύμη φύλλου.', 28),
(2, 'Ανακατέψτε τη φέτα με λίγο γάλα και αυγό για να δημιουργήσετε τη γέμιση.', 28),
(3, 'Απλώστε τη ζύμη φύλλου και βάλτε μια κουταλιά από τη γέμιση στο κέντρο.', 28),
(4, 'Διπλώστε τη ζύμη ώστε να κλείσει καλά τη γέμιση.', 28),
(5, 'Τοποθετήστε τις μπουγάτσες σε ένα ταψί και αλείψτε με λίγο λάδι ή βούτυρο.', 28),
(6, 'Ψήστε σε προθερμασμένο φούρνο μέχρι να ροδίσουν και να γίνουν τραγανές.', 28),
(7, 'Σερβίρετε ζεστές με λίγη ζάχαρη άχνη από πάνω αν θέλετε.', 28),
(1, 'Βράστε τις πέννες σύμφωνα με τις οδηγίες της συσκευασίας.', 29),
(2, 'Σε ένα τηγάνι, σοτάρετε το μπέικον μέχρι να γίνει τραγανό.', 29),
(3, 'Αφαιρέστε το μπέικον και στραγγίστε το σε απορροφητικό χαρτί.', 29),
(4, 'Στο ίδιο τηγάνι, προσθέστε την κρέμα αλφρέντο και ζεστάνετε σε χαμηλή φωτιά.', 29),
(5, 'Προσθέστε τις βρασμένες πέννες στην κρέμα και ανακατέψτε καλά.', 29),
(6, 'Προσθέστε το μπέικον και την τριμμένη παρμεζάνα.', 29),
(7, 'Σερβίρετε αμέσως με επιπλέον παρμεζάνα αν επιθυμείτε.', 29),
(1, 'Προθερμάνετε τον φούρνο στους 180°C.', 30),
(2, 'Θρυμματίστε τα μπισκότα και ανακατέψτε τα με λιωμένο βούτυρο.', 30),
(3, 'Απλώστε το μείγμα μπισκότου σε μια φόρμα και πιέστε το καλά για να δημιουργηθεί η βάση.', 30),
(4, 'Ψήστε τη βάση για 10 λεπτά και αφήστε τη να κρυώσει.', 30),
(5, 'Σε ένα μπολ, ανακατέψτε το τυρί κρέμα, τη ζάχαρη και τη βανίλια μέχρι να ομογενοποιηθούν.', 30),
(6, 'Προσθέστε τα αυγά ένα ένα, ανακατεύοντας καλά.', 30),
(7, 'Ρίξτε το μείγμα τυριού πάνω στη βάση μπισκότου.', 30),
(8, 'Ψήστε για 45-50 λεπτά, μέχρι να στερεοποιηθεί η γέμιση.', 30),
(9, 'Αφήστε το τσιζκέικ να κρυώσει και στη συνέχεια γαρνίρετε με μαρμελάδα μπλεμπέρι.', 30),
(1, 'Κόψτε τις μελιτζάνες σε φέτες και αλατίστε τις για να βγάλουν τα υγρά τους.', 31),
(2, 'Τηγανίστε τις φέτες μελιτζάνας μέχρι να ροδίσουν και στραγγίστε σε απορροφητικό χαρτί.', 31),
(3, 'Σοτάρετε τον κιμά με ψιλοκομμένα κρεμμύδια μέχρι να ροδίσει.', 31),
(4, 'Προσθέστε ντομάτα, κανέλα, αλάτι και πιπέρι και αφήστε να σιγοβράσει.', 31),
(5, 'Κόψτε τις πατάτες σε φέτες και τηγανίστε τις ελαφρώς.', 31),
(6, 'Ετοιμάστε τη μπεσαμέλ: λιώστε βούτυρο, προσθέστε αλεύρι και σταδιακά το γάλα, ανακατεύοντας συνεχώς.', 31),
(7, 'Σε ένα ταψί, στρώστε πατάτες, μελιτζάνες και κιμά και επαναλάβετε.', 31),
(8, 'Καλύψτε με μπεσαμέλ και ψήστε στους 180°C μέχρι να ροδίσει.', 31),
(1, 'Ετοιμάστε τη ζύμη για τα ταρτάκια και ψήστε την σε φορμάκια.', 32),
(2, 'Ετοιμάστε την κρέμα λεμόνι: ανακατέψτε χυμό λεμονιού, ζάχαρη, αυγά και βούτυρο σε κατσαρόλα.', 32),
(3, 'Μαγειρέψτε την κρέμα σε χαμηλή φωτιά μέχρι να πήξει.', 32),
(4, 'Αφήστε την κρέμα να κρυώσει και γεμίστε τα ταρτάκια.', 32),
(5, 'Ετοιμάστε τη μαρέγκα: χτυπήστε ασπράδια αυγών με ζάχαρη μέχρι να σχηματιστούν σφιχτές κορυφές.', 32),
(6, 'Βάλτε τη μαρέγκα πάνω από τα ταρτάκια.', 32),
(7, 'Ψήστε τα ταρτάκια στους 180°C μέχρι να ροδίσει η μαρέγκα.', 32),
(1, 'Σε ένα μπολ, ανακατέψτε τον κιμά με ψιλοκομμένα κρεμμύδια, σκόρδο, μαϊντανό, αλάτι και πιπέρι.', 33),
(2, 'Πλάστε το μείγμα σε μικρά κεφτεδάκια.', 33),
(3, 'Σε μια κατσαρόλα, ζεστάνετε λίγο λάδι και σοτάρετε τα κεφτεδάκια μέχρι να ροδίσουν.', 33),
(4, 'Αφαιρέστε τα κεφτεδάκια από την κατσαρόλα και προσθέστε ψιλοκομμένα κρεμμύδια.', 33),
(5, 'Προσθέστε ντομάτα, αλάτι, πιπέρι και νερό και αφήστε να σιγοβράσει.', 33),
(6, 'Επιστρέψτε τα κεφτεδάκια στην κατσαρόλα και σιγοβράστε για 20-30 λεπτά.', 33),
(7, 'Σερβίρετε τα κεφτεδάκια με φρέσκο μαϊντανό.', 33),
(1, 'Σε μια κατσαρόλα, ζεστάνετε το γάλα και την κρέμα.', 34),
(2, 'Προσθέστε τη ζάχαρη και ανακατέψτε μέχρι να διαλυθεί.', 34),
(3, 'Σε ένα μπολ, χτυπήστε τους κρόκους αυγών.', 34),
(4, 'Προσθέστε σταδιακά το ζεστό μείγμα γάλακτος στους κρόκους, ανακατεύοντας συνεχώς.', 34),
(5, 'Επιστρέψτε το μείγμα στην κατσαρόλα και μαγειρέψτε σε χαμηλή φωτιά μέχρι να πήξει ελαφρώς.', 34),
(6, 'Αφαιρέστε από τη φωτιά και προσθέστε εκχύλισμα βανίλιας.', 34),
(7, 'Αφήστε το μείγμα να κρυώσει και στη συνέχεια παγώστε το σε παγωτομηχανή.', 34),
(1, 'Προθερμάνετε τον φούρνο στους 180°C.', 35),
(2, 'Σε ένα μπολ, ανακατέψτε τη φέτα με αυγά και λίγη ρίγανη.', 35),
(3, 'Απλώστε ένα φύλλο σφολιάτας σε ένα ταψί και απλώστε τη γέμιση από πάνω.', 35),
(4, 'Καλύψτε με το δεύτερο φύλλο σφολιάτας και κλείστε καλά τις άκρες.', 35),
(5, 'Χαράξτε την επιφάνεια της τυρόπιτας και αλείψτε με λίγο λάδι ή βούτυρο.', 35),
(6, 'Ψήστε για 45-50 λεπτά μέχρι να ροδίσει.', 35),
(7, 'Αφήστε την τυρόπιτα να κρυώσει ελαφρώς πριν την κόψετε και σερβίρετε.', 35),
(1, 'Τρίψτε χοντροκομμένα λαχανικά όπως καρότα, κολοκυθάκια και πατάτες.', 36),
(2, 'Σε ένα μπολ, ανακατέψτε τα τριμμένα λαχανικά με αλεύρι και αυγά.', 36),
(3, 'Προσθέστε αλάτι, πιπέρι και μυρωδικά της αρεσκείας σας.', 36),
(4, 'Πλάστε το μείγμα σε κεφτέδες.', 36),
(5, 'Ζεστάνετε λίγο λάδι σε ένα τηγάνι και τηγανίστε τους κεφτέδες μέχρι να ροδίσουν.', 36),
(6, 'Στραγγίστε τους κεφτέδες σε απορροφητικό χαρτί.', 36),
(7, 'Σερβίρετε ζεστούς με σως της επιλογής σας.', 36),
(1, 'Προθερμάνετε τον φούρνο στους 180°C.', 37),
(2, 'Σε ένα μπολ, ανακατέψτε το βούτυρο με τη ζάχαρη μέχρι να αφρατέψει.', 37),
(3, 'Προσθέστε τα αυγά και τη βανίλια και ανακατέψτε καλά.', 37),
(4, 'Σε άλλο μπολ, ανακατέψτε το αλεύρι με τη σόδα και το αλάτι.', 37),
(5, 'Προσθέστε το μείγμα αλευριού στο μείγμα βουτύρου και ανακατέψτε.', 37),
(6, 'Προσθέστε τα κομματάκια σοκολάτας και ανακατέψτε απαλά.', 37),
(7, 'Σχηματίστε μπισκότα και τοποθετήστε τα σε λαδόκολλα.', 37),
(8, 'Ψήστε για 10-12 λεπτά ή μέχρι να ροδίσουν ελαφρώς.', 37),
(1, 'Κόψτε τις πιπεριές και αφαιρέστε τα σπόρια.', 38),
(2, 'Σε ένα τηγάνι, σοτάρετε ψιλοκομμένο κρεμμύδι και κιμά.', 38),
(3, 'Προσθέστε το ρύζι, ντομάτα, αλάτι, πιπέρι και μυρωδικά.', 38),
(4, 'Μαγειρέψτε μέχρι να μαλακώσει το ρύζι.', 38),
(5, 'Γεμίστε τις πιπεριές με το μείγμα και τοποθετήστε τις σε ένα ταψί.', 38),
(6, 'Πασπαλίστε με φέτα τριμμένη.', 38),
(7, 'Ψήστε στους 180°C για 30-40 λεπτά.', 38),
(1, 'Κόψτε το κοτόπουλο σε μικρά κομμάτια.', 39),
(2, 'Μαρινάρετε το κοτόπουλο με λάδι, λεμόνι, σκόρδο, αλάτι και πιπέρι.', 39),
(3, 'Περάστε τα κομμάτια κοτόπουλου σε ξύλινα ξυλάκια.', 39),
(4, 'Ψήστε τα σουβλάκια σε προθερμασμένη σχάρα ή ψηστιέρα.', 39),
(5, 'Σερβίρετε με σως τζατζίκι και ταχίνι.', 39),
(1, 'Λιώστε το βούτυρο και ανακατέψτε με το κανταΐφι.', 40),
(2, 'Στρώστε μισό από το μείγμα σε ένα ταψί.', 40),
(3, 'Απλώστε ομοιόμορφα τα καρύδια στο πάνω μέρος.', 40),
(4, 'Προσθέστε το υπόλοιπο κανταΐφι στο πάνω μέρος.', 40),
(5, 'Ψήστε σε προθερμασμένο φούρνο στους 180°C μέχρι να ροδίσει.', 40),
(6, 'Κατά τη σερβίριση, προσθέστε γενναία ποσότητα σιρόπι στο κανταΐφι.', 40),
(1, 'Κόψτε το φιλέτο σολομού και τα μανιτάρια σε μεγάλα κομμάτια.', 41),
(2, 'Εναλλάξτε τα κομμάτια σολομού και μανιταριών σε ξύλινα ξυλάκια.', 41),
(3, 'Ανακατέψτε τη σάλτσα λεμονιού με καπνιστό αλάτι.', 41),
(4, 'Βουτήξτε τα ξυλάκια με τον σολομό και τα μανιτάρια στη σάλτσα.', 41),
(5, 'Ψήστε σε προθερμασμένη σχάρα μέχρι ο σολομός να ψηθεί και να μαλακώσουν τα μανιτάρια.', 41),
(6, 'Σερβίρετε ζεστό.', 41),
(1, 'Σε ένα τηγάνι, σοτάρετε ψιλοκομμένο κρεμμύδι και σκόρδο.', 42),
(2, 'Προσθέστε το ρύζι και σοτάρετε μέχρι να γίνει διαφανές.', 42),
(3, 'Προσθέστε τον σάφραν και ανακατέψτε καλά.', 42),
(4, 'Προσθέστε τον ζωμό κρέατος μερικές κουταλιές τη φορά.', 42),
(5, 'Αφήστε το να βράσει μέχρι να απορροφηθεί ο ζωμός.', 42),
(6, 'Αφαιρέστε από τη φωτιά και προσθέστε το λεμονοτσούκνιδο και το τυρί παρμεζάνα.', 42),
(7, 'Ανακατέψτε καλά και σερβίρετε ζεστό.', 42),
(1, 'Σε ένα βαθύ τηγάνι, σοτάρετε τα κομμάτια αρνί μέχρι να πάρουν χρώμα.', 43),
(2, 'Προσθέστε τα κρεμμυδένια και αρωματικά στοιχεία όπως σκόρδο, κόκκινο κρασί και μπαχαρικά.', 43),
(3, 'Σιγοβράστε για περίπου 2-3 ώρες μέχρι το αρνί να μαλακώσει και η σάλτσα να ενσωματωθεί.', 43),
(4, 'Σερβίρετε ζεστό, συνοδευόμενο από ρύζι ή πουρέ πατάτας.', 43),
(1, 'Προθερμάνετε τον φούρνο στους 180°C και λαδώστε ένα ταψί για κέικ.', 44),
(2, 'Ανακατέψτε τα στερεά υλικά όπως αλεύρι, κακάο, ζάχαρη και μαγιά σε ένα μπολ.', 44),
(3, 'Προσθέστε τα υγρά υλικά όπως αβγά, γάλα και λάδι και ανακατέψτε καλά.', 44),
(4, 'Προσθέστε τα φρούτα του δάσους και ανακατέψτε απαλά.', 44),
(5, 'Χύστε το μείγμα στο ταψί και ψήστε για περίπου 30-40 λεπτά.', 44),
(6, 'Αφήστε το κέικ να κρυώσει πριν το κόψετε σε κομμάτια.', 44),
(1, 'Σε ένα τηγάνι, σοτάρετε τα θαλασσινά μέχρι να πάρουν χρώμα.', 45),
(2, 'Προσθέστε τα μπέικον και τα λαχανικά και σοτάρετε για λίγα λεπτά ακόμα.', 45),
(3, 'Προετοιμάστε το γκούφρο όπως αναγράφεται στις οδηγίες στη συσκευασία.', 45),
(4, 'Σερβίρετε τα θαλασσινά και τα λαχανικά πάνω από τον γκούφρο και προσθέστε σάλτσα λευκού κρασιού.', 45),
(1, 'Βράστε το κριθαράκι σύμφωνα με τις οδηγίες στη συσκευασία.', 46),
(2, 'Σοτάρετε το φιλέτο κοτόπουλου μέχρι να ροδίσει.', 46),
(3, 'Προσθέστε τα αρωματικά λαχανικά όπως καρότα και σέλινο και σοτάρετε για λίγα λεπτά ακόμα.', 46),
(4, 'Προσθέστε τον σως λεμονάτο και ανακατέψτε καλά.', 46),
(5, 'Σερβίρετε το φιλέτο σε πιάτο με το κριθαράκι.', 46),
(1, 'Βράστε τα ταλιατέλες σύμφωνα με τις οδηγίες στη συσκευασία.', 47),
(2, 'Σοτάρετε την κολοκύθα μέχρι να μαλακώσει αλλά να διατηρήσει τη σφριγηλότητά της.', 47),
(3, 'Προσθέστε το φυστικοβούτυρο στην κολοκύθα και ανακατέψτε καλά.', 47),
(4, 'Ανακατέψτε τα ραβασάκια με την κολοκύθα και τη ρίγανη.', 47),
(5, 'Σερβίρετε με παρμεζάνα.', 47),
(1, 'Προθερμάνετε τον φούρνο στους 180°C.', 48),
(2, 'Αλείψτε το φιλέτο με ελαιόλαδο και περιποιηθείτε το με σκόρδο και δεντρολίβανο.', 48),
(3, 'Ψήστε στον φούρνο για περίπου 30-40 λεπτά μέχρι να ψηθεί το μοσχάρι στο επιθυμητό επίπεδο ψησίματος.', 48),
(4, 'Αφήστε το να ξεκουραστεί για λίγο πριν το κόψετε σε φέτες.', 48),
(1, 'Προθερμάνετε το φούρνο στους 200°C και ετοιμάστε ένα ταψί.', 49),
(2, 'Κόψτε τα πεπερόνια στη μέση και αφαιρέστε τους σπόρους.', 49),
(3, 'Τοποθετήστε τα πεπερόνια στο ταψί και ψήστε για περίπου 15-20 λεπτά.', 49),
(4, 'Κατά τη διάρκεια του ψησίματος, ανακατέψτε μελιτζάνα και τυρί φέτα στο εσωτερικό κάθε πεπερόνιου.', 49),
(5, 'Μετά το ψήσιμο, προσθέστε το μέλι σε κάθε πεπερόνι και επιστρέψτε στο φούρνο για άλλα 5 λεπτά.', 49),
(6, 'Σερβίρετε ζεστά ως ορεκτικό ή ως μεζέ.', 49),
(1, 'Ανοίξτε το στήθος κοτόπουλου και γεμίστε το με φρέσκο ροκφόρ.', 50),
(2, 'Κλείστε το στήθος και δέστε το καλά με κουβάδες κοτόπουλου.', 50),
(3, 'Σε ένα τηγάνι, σοτάρετε το μπριός στήθος μέχρι να πάρει χρώμα.', 50),
(4, 'Προσθέστε τη σάλτσα λευκού κρασιού και σιγοβράστε για 15-20 λεπτά.', 50),
(5, 'Σερβίρετε ζεστό με συνοδευτικά όπως πουρέ πατάτας ή ρύζι.', 50),
(1, 'Ψήστε το μπριός μοσχαρίσιο μέχρι να είναι μέτρια ψημένο.', 51),
(2, 'Σε ένα μικρό τηγάνι, ζεστάνετε τη σάλτσα μαύρης τρούφας σε χαμηλή φωτιά.', 51),
(3, 'Σερβίρετε το μπριός μοσχαρίσιο σε πιάτο και περιχύστε με τη σάλτσα μαύρης τρούφας.', 51),
(4, 'Συνοδεύστε με πουρέ πατάτας με κρέμα και λίγα φρέσκα βότανα.', 51),
(1, 'Βράστε τα λαχανικά μέχρι να μαλακώσουν αλλά να διατηρήσουν τη σφριγηλότητά τους.', 52),
(2, 'Ανακατέψτε τα λαχανικά με την τριμμένη παρμεζάνα και τα φρέσκα βότανα.', 52),
(3, 'Σε ένα μπολ, χτυπήστε τα αβγά και ανακατέψτε τα με τα λαχανικά.', 52),
(4, 'Μεταφέρετε το μείγμα σε ένα ταψί και ψήστε στον φούρνο για περίπου 30-40 λεπτά.', 52),
(5, 'Σερβίρετε ζεστό ως παραδοσιακό φαγητό και συνοδεύστε με φρέσκο ψωμί.', 52),
(1, 'Σοτάρετε τα παϊδάκια μοσχαρίσια σε ένα τηγάνι μέχρι να πάρουν χρώμα.', 53),
(2, 'Προσθέστε το μέλι και το κίτρο και ανακατέψτε καλά μέχρι να ενσωματωθούν.', 53),
(3, 'Προσθέστε λίγο νερό και αφήστε τα παϊδάκια να σιγοβράσουν μέχρι να μαλακώσουν.', 53),
(4, 'Σερβίρετε ζεστά με συνοδευτικά όπως ρύζι ή πουρέ πατάτας.', 53),
(1, 'Σε μια κατσαρόλα, σοτάρετε τις σπαράγγιες μέχρι να μαλακώσουν ελαφρά.', 54),
(2, 'Προσθέστε την κρέμα καρύδας και το λεμονοτζίντζερ και ανακατέψτε καλά.', 54),
(3, 'Αφήστε τη σούπα να σιγοβράσει για 10-15 λεπτά ώσπου να ενωθούν οι γεύσεις.', 54),
(4, 'Σερβίρετε ζεστή, στολίζοντας με φρέσκα φύλλα μέντας ή κόλιανδρου.', 54),
(1, 'Προθερμάνετε τον φούρνο στους 180°C.', 55),
(2, 'Τοποθετήστε τα φιλέτα γαλοπούλας σε ένα ταψί.', 55),
(3, 'Ανακατέψτε το ροζ πιπέρι και το λεμονόχορτο με το ελαιόλαδο και απλώστε το μείγμα πάνω από τη γαλοπούλα.', 55),
(4, 'Ψήστε στον προθερμασμένο φούρνο για περίπου 25-30 λεπτά μέχρι να ψηθεί και να πάρει χρυσαφί χρώμα.', 55),
(5, 'Σερβίρετε ζεστό με πλάι συνοδευτικά όπως πουρέ πατάτας και πράσινα λαχανικά.', 55);
